const STORAGE_KEY = 'brown-ia-session-v2';
const SETTINGS_KEY = 'brown-ia-settings-v1';
const KEY_STORAGE = 'brown-gemini-key-v1';
const UNIVERSAL_KEY = String(window.BROWN_CONFIG?.universalKey || '').trim();
const FILE_DB = 'brown-ia-files-v1';
const CHATS_KEY = 'brown-ia-chats-v1';
const PROJECTS_KEY = 'brown-ia-projects-v1';
let fileReady;
const $ = (selector) => document.querySelector(selector);
const savedSettings = (() => { try { return JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}'); } catch { return {}; } })();
const state = { chatId: `chat-${Date.now()}`, chats: loadChats(), projects: loadProjects(), pendingFile: null, lastFile: null, textModel: null, modelLimits: { input: 32768, output: 8192 }, profile: savedSettings.profile === 'CODE' ? 'CODE' : 'BROWN', thinking: savedSettings.thinking || 'MEDIO', language: savedSettings.language || 'pt-BR', messages: loadMessages(), apiKey: null, model: null };
const copy = {
  'pt-BR': { ready: 'Conversa pronta.', prompt: 'Faça uma pergunta, peça um plano ou descreva algo que a Brown deve criar.', greeting: 'Olá. Estou pronta para ajudar. Descreva o que você precisa fazer.', wellbeing: 'Tudo funcionando por aqui. Posso ajudar com conversa, código, pesquisa ou criação de arquivos.', demo: 'Entendi o pedido. Nesta primeira versão, estou no modo de demonstração local. O próximo conector permitirá gerar, validar e baixar arquivos reais com confirmação do resultado.', generic: p => `Recebi sua mensagem no perfil ${p}. O site está funcionando em modo local de demonstração; o próximo passo é conectar o provedor de IA com segurança.`, note: 'Brown responderá em português.', tag: 'PT-BR' },
  en: { ready: 'Conversation ready.', prompt: 'Ask a question, request a plan, or describe something Brown should create.', greeting: 'Hello. I am ready to help. Tell me what you need to do.', wellbeing: 'Everything is working. I can help with conversation, code, research, or file creation.', demo: 'I understood the request. This first version is running in local demo mode. The next connector will generate, validate, and download real files.', generic: p => `I received your message in the ${p} profile. The site is running in local demo mode; the next step is to connect the AI provider securely.`, note: 'Brown will respond in English.', tag: 'EN' },
  es: { ready: 'Conversación lista.', prompt: 'Haz una pregunta, pide un plan o describe algo que Brown deba crear.', greeting: 'Hola. Estoy lista para ayudar. Describe lo que necesitas hacer.', wellbeing: 'Todo funciona correctamente. Puedo ayudar con conversación, código, investigación o archivos.', demo: 'Entendí la solicitud. Esta primera versión funciona en modo de demostración local. El próximo conector generará y validará archivos reales.', generic: p => `Recibí tu mensaje en el perfil ${p}. El sitio funciona en modo local; el siguiente paso es conectar el proveedor de IA de forma segura.`, note: 'Brown responderá en español.', tag: 'ES' }
};
function lang() { return state.language === 'auto' ? 'pt-BR' : state.language; }
function t(key, ...args) { const value = copy[lang()][key]; return typeof value === 'function' ? value(...args) : value; }
function openFileDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(FILE_DB, 1); request.onupgradeneeded = () => request.result.createObjectStore('attachments'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function saveLastFile(file) { try { const db = await openFileDb(); db.transaction('attachments', 'readwrite').objectStore('attachments').put(file, 'last'); } catch {} }
async function loadLastFile() { try { const db = await openFileDb(); return await new Promise(resolve => { const request = db.transaction('attachments').objectStore('attachments').get('last'); request.onsuccess = () => resolve(request.result || null); request.onerror = () => resolve(null); }); } catch { return null; } }
fileReady = loadLastFile().then(file => { if (file) state.lastFile = file; });
function loadMessages() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); } catch { return []; } }
function loadChats() { try { const chats = JSON.parse(localStorage.getItem(CHATS_KEY) || '[]'); return Array.isArray(chats) ? chats : []; } catch { return []; } }
function loadProjects() { try { const projects = JSON.parse(localStorage.getItem(PROJECTS_KEY) || '[]'); return Array.isArray(projects) ? projects : []; } catch { return []; } }
function chatTitle(messages) { const first = messages.find(message => message.role === 'user'); return String(first?.content || 'Nova conversa').replace(/\s+/g, ' ').slice(0, 42); }
function renderChatList() { const root = $('#chatList'); if (!root) return; const chats = [...state.chats].sort((a,b) => b.updatedAt - a.updatedAt); $('#chatCount').textContent = chats.length; root.innerHTML = chats.length ? chats.slice(0, 20).map(chat => `<button class="chat-item ${chat.id === state.chatId ? 'active' : ''}" type="button" data-chat-id="${escapeText(chat.id)}"><span>◌ ${escapeText(chat.title || 'Nova conversa')}</span><small>${chat.messages?.length || 0}</small></button>`).join('') : '<small class="project-list">Nenhuma conversa salva</small>'; }
function renderProjects() { const root = $('#projectList'); if (!root) return; root.innerHTML = state.projects.length ? state.projects.map(project => `<button class="project-item" type="button"><span>▣ ${escapeText(project)}</span></button>`).join('') : '<small>Nenhum projeto criado</small>'; }
function persist() { const cleanMessages = state.messages.map(({ imageData, ...message }) => message); const current = { id: state.chatId, title: chatTitle(cleanMessages), messages: cleanMessages, updatedAt: Date.now() }; const index = state.chats.findIndex(chat => chat.id === state.chatId); if (index >= 0) state.chats[index] = current; else state.chats.push(current); state.chats = state.chats.filter(chat => chat.messages?.length || chat.id === state.chatId).slice(-20); localStorage.setItem(STORAGE_KEY, JSON.stringify(cleanMessages)); localStorage.setItem(CHATS_KEY, JSON.stringify(state.chats)); localStorage.setItem(PROJECTS_KEY, JSON.stringify(state.projects)); localStorage.setItem(SETTINGS_KEY, JSON.stringify({ profile: state.profile, thinking: state.thinking, language: state.language, chatId: state.chatId })); $('#messageCount').textContent = state.messages.length; renderChatList(); renderProjects(); }
function formatContent(value) { const escaped = escapeText(value); const markdown = escaped.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a class=\"smart-link\" href=\"$2\" target=\"_blank\" rel=\"noopener noreferrer\">↗ $1</a>'); return markdown.split('\n').map(line => { const trimmed = line.trim(); if (/^https?:\/\/[^\s<]+$/.test(trimmed)) return `<a class=\"standalone-link\" href=\"${trimmed}\" target=\"_blank\" rel=\"noopener noreferrer\"><span>↗</span><strong>Abrir link</strong><small>${trimmed}</small></a>`; return line.replace(/(https?:\/\/[^\s<]+)/g, '<a class=\"smart-link\" href=\"$1\" target=\"_blank\" rel=\"noopener noreferrer\">↗ $1</a>'); }).join('\n'); }
function escapeText(value) { return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function renderMessages() {
  const root = $('#messages');
  if (!state.messages.length) { root.innerHTML = `<div class="empty-state" id="emptyState"><div class="empty-glyph">BR</div><div class="empty-kicker">SYSTEM ONLINE · READY FOR INPUT</div><h2>${t('ready')}</h2><p>${t('prompt')}</p><div class="quick-prompts"><button data-prompt="Explique como você pode me ajudar.">Conhecer a Brown <span>↗</span></button><button data-prompt="Crie um plano profissional para meu projeto.">Criar um plano <span>↗</span></button><button data-prompt="Analise esta ideia e sugira melhorias.">Analisar uma ideia <span>↗</span></button></div></div>`; persist(); return; }
  root.innerHTML = state.messages.map((m, index) => { const feedback = m.feedback || ''; return `<article class="message ${m.role}" data-message-index="${index}"><div class="avatar">${m.role === 'user' ? 'OP' : 'BR'}</div><div class="message-body"><div class="message-label">${m.role === 'user' ? 'OPERADOR' : 'BROWN'}</div><div class="message-content">${formatContent(m.content)}${m.attachmentName ? `<div class="attachment-chip">📎 ${escapeText(m.attachmentName)}</div>` : ''}<div class="message-actions"><button type="button" data-message-action="copy" title="Copiar">⧉</button>${m.role === 'user' ? '<button type="button" data-message-action="edit" title="Editar mensagem">✎</button>' : `<a class="download-response" href="data:text/markdown;charset=utf-8,${encodeURIComponent(m.content)}" download="brown-resposta.md" title="Baixar resposta">↓ .md</a>`}<button type="button" class="feedback-btn ${feedback === 'up' ? 'selected' : ''}" data-message-action="up" title="Boa resposta">＋</button><button type="button" class="feedback-btn ${feedback === 'down' ? 'selected' : ''}" data-message-action="down" title="Resposta precisa melhorar">−</button></div></div></div></article>`; }).join(''); root.scrollTop = root.scrollHeight; persist();
}
function handleMessageAction(event) {
  const button = event.target.closest('[data-message-action]'); if (!button) return;
  const article = button.closest('[data-message-index]'); const index = Number(article?.dataset.messageIndex); const message = state.messages[index]; if (!message) return;
  const action = button.dataset.messageAction;
  if (action === 'copy') { if (navigator.clipboard) navigator.clipboard.writeText(message.content); button.textContent = '✓'; setTimeout(() => { button.textContent = '⧉'; }, 900); return; }
  if (action === 'edit') { state.editingIndex = index; $('#promptInput').value = message.content; $('#promptInput').focus(); $('#promptInput').setSelectionRange(message.content.length, message.content.length); return; }
  if (action === 'up' || action === 'down') { message.feedback = message.feedback === action ? '' : action; renderMessages(); }
}
function localReply(input) { const text = input.toLowerCase().trim(); if (/^(oi|olá|ola|hello|hi|hola|e aí|e ai|bom dia|boa tarde|boa noite)[!. ]*$/.test(text)) return t('greeting'); if (/^(tudo bem|how are you|todo bien)/.test(text)) return t('wellbeing'); if (text.includes('gemini')) return lang() === 'en' ? 'The Gemini connector is not active yet. The interface is ready for a secure backend without exposing the key in the browser.' : lang() === 'es' ? 'El conector Gemini aún no está activo. La interfaz está preparada para un backend seguro sin exponer la clave.' : 'O conector Gemini ainda não está ativo nesta versão. A interface está preparada para receber um backend seguro sem expor a chave no navegador.'; if (text.includes('arquivo') || text.includes('html') || text.includes('código') || text.includes('codigo') || text.includes('file') || text.includes('code')) return t('demo'); return t('generic', state.profile); }
function fetchWithTimeout(url, options = {}, ms = 30000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), ms); return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timer)).catch(error => { if (error.name === 'AbortError') throw new Error(`A Gemini demorou mais de ${Math.round(ms / 1000)} segundos para responder.`); throw new Error('Não foi possível alcançar a Gemini. Verifique sua conexão e as permissões da chave.'); }); }
async function validateGeminiKey(key) { const response = await fetchWithTimeout(`https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(key)}`, {}, 10000); let payload = {}; try { payload = await response.json(); } catch {} if (!response.ok) { const message = payload?.error?.message || `HTTP ${response.status}`; throw new Error(message.replace(/AIza\S+/g, '[chave omitida]')); } const models = (payload.models || []).filter(model => (model.supportedGenerationMethods || []).includes('generateContent')); const names = models.map(model => String(model.name || '').replace(/^models\//, '')); const preferred = ['gemini-3.5-flash-lite','gemini-2.0-flash-lite','gemini-3.8-flash-lite','gemini-3.8-flash','gemini-3.5-flash','gemini-2.5-flash','gemini-2.0-flash','gemini-1.5-flash']; const selected = preferred.find(name => names.includes(name)) || names.find(name => /flash.*lite/i.test(name)) || names.find(name => /flash/i.test(name)); if (!selected) throw new Error('A chave é válida, mas nenhum modelo Flash compatível foi encontrado.'); const selectedInfo = models.find(model => String(model.name || '').replace(/^models\//, '') === selected) || {}; return { selected, limits: { input: Number(selectedInfo.inputTokenLimit) || 32768, output: Number(selectedInfo.outputTokenLimit) || 8192 } }; }
async function geminiReply(input, file = null) {
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${state.model}:generateContent?key=${encodeURIComponent(state.apiKey)}`;
  const codeTask = /(c[oó]digo|programa|script|html|css|javascript|python|bash|terminal|fun[cç][aã]o|bug|erro|arquivo|documento)/i.test(input);
  const researchTask = /(pesquise|pesquisa|compare|fontes|referências|hist[oó]ria|dados|atual|link)/i.test(input);
  const continuation = /(continue|continuar|parte seguinte|parte 2|cortad[oa]|incomplet[oa]|parou no meio|faltou|não terminou|nao terminou|sem cortar|completo|inteiro|todos os arquivos)/i.test(input);
  const expansion = continuation || /(detalhado|detalhada|profissional|completo|completa|grande|extenso|extensa|passo a passo|produção|producao|pronto para usar|sem limite)/i.test(input);
  const fileTask = Boolean(file);
  const visualTask = Boolean(file && /^image\//i.test(file.mimeType));
  const modelInput = Math.max(16000, Number(state.modelLimits?.input) || 32768);
  const historyBudget = Math.min(110000, Math.max(24000, (modelInput - 7000) * 3.2));
  let used = 0;
  const history = [];
  for (const message of [...state.messages].reverse()) {
    const text = String(message.content || '').slice(0, 9000);
    if (history.length && used + text.length > historyBudget) break;
    history.unshift({ role: message.role === 'assistant' ? 'model' : 'user', parts: [{ text }] });
    used += text.length;
  }
  if (file && history.length) {
    history[history.length - 1].parts[0].text += `\n\n[Arquivo anexado: ${file.name} | MIME: ${file.mimeType} | tamanho: ${file.size || 'desconhecido'} bytes]`;
    if (/^(text\/|application\/(pdf|json|xml)|text\/csv)/i.test(file.mimeType)) {
      history[history.length - 1].parts.push({ inlineData: { mimeType: file.mimeType, data: file.base64 } });
    }
  }
  const thinkingGuide = {
    LEVE: 'Resolva rapidamente e mantenha a resposta direta. Use o orçamento padrão, mas nunca abandone uma instrução essencial.',
    MEDIO: 'Analise a lógica principal, confira a resposta e entregue profundidade equilibrada.',
    ALTO: 'Verifique casos-limite, consistência, requisitos e possíveis erros antes de responder.',
    EXTREMO: 'Faça uma revisão rigorosa de requisitos, exceções, completude e qualidade antes de responder.'
  }[state.thinking] || 'Analise e responda com equilíbrio.';
  const links = input.match(/https?:\/\/[^\s)]+/gi) || [];
  const profileGuide = state.profile === 'CODE' ? 'Perfil Code ativo: priorize arquitetura, código executável, arquivos completos, depuração, testes, segurança e instruções precisas. Para pedidos de programação, aja como uma engenheira de software sênior e entregue implementação real, não apenas sugestões.' : 'Perfil Brown ativo: responda de forma versátil, clara e prática para conversa, análise, pesquisa, planejamento e criação.'; const system = `Você é Brown, uma assistente profissional, versátil e prática. ${profileGuide} Perfil: ${state.profile}. Nível de raciocínio: ${state.thinking}. ${thinkingGuide} Idioma obrigatório: ${lang()}. Tarefa de código/documento: ${codeTask ? 'sim' : 'não'}. Tarefa de pesquisa: ${researchTask ? 'sim' : 'não'}. Arquivo anexado: ${fileTask ? `${file.name} (${file.mimeType})` : 'não'}. Imagem anexada: ${visualTask ? 'sim' : 'não'}. Expansão solicitada: ${expansion ? 'sim' : 'não'}.

Responda ao pedido real, sem saudações automáticas, persona teatral, status inventado ou explicações sobre ser uma IA. Não diga que é incapaz apenas por ser uma assistente de texto. Para pedidos benignos, resolva diretamente. Não use recusas genéricas: explique somente uma limitação concreta quando ela realmente existir. Não invente fatos, resultados de ferramentas, acesso a links ou alterações que não foram executadas.

Para código e arquivos, entregue uma solução funcional, completa e preservada. Não corte no meio, não troque partes por TODO e não omita arquivos necessários. Se o usuário pedir alteração, devolva a versão integral revisada e indique nome/extensão. Se a resposta não couber em uma saída, divida em partes sequenciais completas, sem perder conteúdo, e termine informando a próxima parte necessária. Se o usuário pediu continuação, continue exatamente a partir do ponto anterior e não repita o que já foi entregue.

Para pesquisa, diferencie fatos, inferências e incertezas. Para links, use apenas conteúdo fornecido ou acessível; nunca finja ter aberto uma página. Use Markdown quando melhorar a leitura. Não revele raciocínio interno passo a passo; forneça conclusões, verificações e justificativas úteis. Só recuse pedidos que envolvam dano grave, crime ou abuso perigoso.

VISÃO E ARQUIVOS: quando houver imagem, faça inspeção literal e conservadora. Leia texto somente se os caracteres estiverem realmente visíveis; preserve exatamente a grafia observada e, se estiver ilegível, diga 'não consigo confirmar' em vez de adivinhar. Descreva objetos, cores, padrões e formas separando observação direta, hipótese e o que não é possível concluir. Não transforme pontos, ruído ou padrões ambíguos em galáxias, núcleos ou outros objetos específicos sem evidência clara. Se o usuário perguntar o que está escrito, responda somente com a transcrição verificável e indique trechos incertos.

EXECUÇÃO E INTENÇÃO: identifique o verbo e o objeto principal antes de responder. Se o usuário pedir uma ação concreta, explique ou produza essa ação; não substitua andar, mover, clicar ou executar por um background, imagem, decoração ou descrição visual. Se houver ambiguidade material, faça uma pergunta curta. Seja calorosa e direta, com pequenas reações naturais quando cabível, sem persona teatral, status inventado ou saudações repetidas. Links detectados: ${links.join(', ') || 'nenhum'}.`;
  const standardOutput = codeTask ? (state.thinking === 'LEVE' ? 2048 : state.thinking === 'MEDIO' ? 4096 : state.thinking === 'ALTO' ? 6144 : 8192) : (state.thinking === 'LEVE' ? 768 : state.thinking === 'MEDIO' ? 1536 : state.thinking === 'ALTO' ? 3072 : 4096);
  const expandedOutput = codeTask ? 32768 : 16384;
  const desiredOutput = expansion ? expandedOutput : standardOutput;
  const outputLimit = Math.min(desiredOutput, Number(state.modelLimits?.output) || 8192);
  const generationConfig = { temperature: visualTask ? 0.15 : state.thinking === 'LEVE' ? 0.7 : state.thinking === 'MEDIO' ? 0.55 : state.thinking === 'ALTO' ? 0.4 : 0.25, topP: visualTask ? 0.8 : 0.95, maxOutputTokens: outputLimit };
  const request = async (contents, timeout) => {
    const response = await fetchWithTimeout(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents, generationConfig }) }, timeout);
    let payload = {};
    try { payload = await response.json(); } catch {}
    if (!response.ok) { const message = payload?.error?.message || `HTTP ${response.status}`; throw new Error(message.replace(/AIza\S+/g, '[chave omitida]')); }
    const candidate = payload?.candidates?.[0];
    const text = candidate?.content?.parts?.map(part => part.text || '').join('').trim();
    if (!text) throw new Error('A Gemini não retornou texto.');
    return { text, truncated: candidate?.finishReason === 'MAX_TOKENS' };
  };
  const timeout = expansion || codeTask || fileTask ? 90000 : 35000;
  const first = await request(history, timeout);
  if (!first.truncated || (!codeTask && !expansion)) return first.text;
  const continuationHistory = [...history, { role: 'model', parts: [{ text: first.text }] }, { role: 'user', parts: [{ text: 'Continue exatamente do ponto em que a resposta foi interrompida. Não repita o conteúdo anterior. Entregue apenas a continuação completa.' }] }];
  const second = await request(continuationHistory, timeout);
  return `${first.text}\n\n${second.text}`;
}
function revealKeyFallback() { /* A conexão é automática; nenhuma chave é exibida na interface. */ }
function showQuotaFallback(message) { const notice = $('#modeNotice'); notice.hidden = false; $('#modeTitle').textContent = 'Provedor temporariamente indisponível'; const detail = message && /limit|quota|429|resource exhausted/i.test(message) ? message.replace(/AIza\S+/g, '[credencial omitida]').slice(0, 180) : 'O provedor não aceitou a solicitação.'; $('#modeDescription').textContent = `A conexão automática não pôde concluir a solicitação. ${detail}`; }
function setConnectionStatus(status, message) { const statusText = $('#statusText'); if (status === 'connected') { $('#modeTitle').textContent = 'Conexão ativa'; $('#modeDescription').textContent = 'A Brown está pronta para responder.'; if (statusText) statusText.textContent = 'GEMINI READY'; } else if (status === 'error') { if (statusText) statusText.textContent = 'GEMINI ERROR'; } else if (statusText) statusText.textContent = 'LOCAL READY'; }
function showProviderSetup(message = 'Nenhuma conexão validada.') { const setup = $('#providerSetup'); if (setup) setup.hidden = false; const status = $('#initialProviderStatus'); if (status) status.textContent = message; }
function hideProviderSetup() { const setup = $('#providerSetup'); if (setup) setup.hidden = true; }
function updateTags() { $('#channelTitle').textContent = state.profile === 'BROWN' ? 'Brown' : 'Code'; $('#profileTag').textContent = state.profile; $('#thinkingTag').textContent = state.thinking === 'MEDIO' ? 'MÉDIO' : state.thinking; $('#thinkingButtonLabel').textContent = state.thinking === 'MEDIO' ? 'MÉDIO' : state.thinking; $('#languageTag').textContent = copy[lang()].tag; $('#languageNote').textContent = t('note'); $('#languageSelect').value = state.language; }
function setActive(selector, attr, value) { document.querySelectorAll(selector).forEach(el => el.classList.toggle('active', el.dataset[attr] === value)); }
function closeMenu() { const menu = $('#appMenu'); if (menu) { menu.classList.remove('menu-open'); $('#menuToggle').setAttribute('aria-expanded', 'false'); } }
function openMenu() { const menu = $('#appMenu'); if (menu) { menu.classList.add('menu-open'); $('#menuToggle').setAttribute('aria-expanded', 'true'); } }
$('#menuToggle').addEventListener('click', () => { const open = $('#appMenu').classList.contains('menu-open'); open ? closeMenu() : openMenu(); });
$('#menuClose').addEventListener('click', closeMenu);
$('#newChatBtn').addEventListener('click', () => { persist(); state.chatId = `chat-${Date.now()}`; state.messages = []; state.pendingFile = null; renderMessages(); openMenu(); });
$('#chatList').addEventListener('click', e => { const item = e.target.closest('[data-chat-id]'); if (!item) return; const chat = state.chats.find(entry => entry.id === item.dataset.chatId); if (!chat) return; state.chatId = chat.id; state.messages = Array.isArray(chat.messages) ? chat.messages : []; renderMessages(); closeMenu(); });
$('#newProjectBtn').addEventListener('click', () => { const name = prompt('Nome do projeto:'); if (!name?.trim()) return; state.projects.push(name.trim().slice(0, 60)); persist(); });
function syncSettingsPanel() { const language = $('#settingsLanguageSelect'); if (language) language.value = state.language; document.querySelectorAll('[data-settings-profile]').forEach(button => button.classList.toggle('active', button.dataset.settingsProfile === state.profile)); document.querySelectorAll('[data-settings-thinking]').forEach(button => button.classList.toggle('active', button.dataset.settingsThinking === state.thinking)); const providerStatus = $('#providerSettingsStatus'); if (providerStatus) providerStatus.textContent = state.apiKey ? `Conectado · ${state.model || 'modelo validado'}` : 'Não conectado. A Brown usará o modo local até validar uma chave.'; }
$('#settingsMenuBtn').addEventListener('click', () => { const panel = $('#settingsPanel'); panel.hidden = !panel.hidden; if (!panel.hidden) syncSettingsPanel(); });
$('#settingsClose').addEventListener('click', () => { $('#settingsPanel').hidden = true; });
$('#providerApplyBtn').addEventListener('click', async () => { const input = $('#providerKeyInput'); const button = $('#providerApplyBtn'); const value = input.value.trim(); const status = $('#providerSettingsStatus'); if (!value) { status.textContent = 'Cole uma chave para validar.'; return; } button.disabled = true; button.textContent = 'Validando...'; const ok = await connectGemini(value, false); if (ok) { if ($('#providerSaveKey').checked) localStorage.setItem(KEY_STORAGE, value); else localStorage.removeItem(KEY_STORAGE); input.value = ''; status.textContent = `Conectado · ${state.model}`; $('#modeNotice').hidden = true; $('#channelMode').textContent = 'GEMINI'; hideProviderSetup(); } else { status.textContent = 'Não foi possível validar esta chave.'; } button.disabled = false; button.textContent = 'Validar e usar'; });
$('#providerClearBtn').addEventListener('click', () => { localStorage.removeItem(KEY_STORAGE); state.apiKey = null; state.model = null; state.textModel = null; setConnectionStatus('idle'); $('#channelMode').textContent = 'LOCAL DEMO'; $('#modeNotice').hidden = false; $('#modeTitle').textContent = 'Modo local'; $('#modeDescription').textContent = 'Nenhum provedor validado. Conecte uma chave para ativar a Brown.'; $('#providerKeyInput').value = ''; showProviderSetup(); syncSettingsPanel(); });
$('#initialConnectBtn').addEventListener('click', async () => { const input = $('#initialKeyInput'); const button = $('#initialConnectBtn'); const status = $('#initialProviderStatus'); const value = input.value.trim(); if (!value) { status.textContent = 'Cole uma chave Gemini antes de conectar.'; return; } button.disabled = true; button.textContent = 'VALIDANDO...'; status.textContent = 'Consultando o provedor...'; const ok = await connectGemini(value, false); if (ok) { localStorage.setItem(KEY_STORAGE, value); input.value = ''; $('#modeNotice').hidden = true; $('#channelMode').textContent = 'GEMINI'; hideProviderSetup(); syncSettingsPanel(); } else { status.textContent = 'Não foi possível validar a chave. Confira o valor e tente novamente.'; } button.disabled = false; button.textContent = 'CONECTAR'; });
$('#settingsLanguageSelect').addEventListener('change', e => { state.language = e.target.value; updateTags(); renderMessages(); persist(); syncSettingsPanel(); });
document.querySelectorAll('[data-settings-profile]').forEach(button => button.addEventListener('click', () => { state.profile = button.dataset.settingsProfile; setActive('.profile-btn','profile',state.profile); updateTags(); persist(); syncSettingsPanel(); }));
document.querySelectorAll('[data-settings-thinking]').forEach(button => button.addEventListener('click', () => { state.thinking = button.dataset.settingsThinking; updateTags(); persist(); syncSettingsPanel(); }));
$('#profileList').addEventListener('click', e => { const btn = e.target.closest('[data-profile]'); if (!btn) return; state.profile = btn.dataset.profile; setActive('.profile-btn','profile',state.profile); updateTags(); persist(); });
$('#thinkingButton').addEventListener('click', () => { const menu = $('#thinkingMenu'); const open = menu.hidden; menu.hidden = !open; $('#thinkingButton').setAttribute('aria-expanded', String(open)); });
$('#thinkingMenu').addEventListener('click', e => { const btn = e.target.closest('[data-thinking]'); if (!btn) return; state.thinking = btn.dataset.thinking; updateTags(); persist(); $('#thinkingMenu').hidden = true; $('#thinkingButton').setAttribute('aria-expanded', 'false'); });
document.addEventListener('click', e => { if (!e.target.closest('.reasoning-picker')) { $('#thinkingMenu').hidden = true; $('#thinkingButton').setAttribute('aria-expanded', 'false'); } });
$('#languageSelect').addEventListener('change', e => { state.language = e.target.value; updateTags(); renderMessages(); });
async function connectGemini(value, silent = false) { if (!value) { state.apiKey = null; state.model = null; state.textModel = null; state.modelLimits = { input: 32768, output: 8192 }; setConnectionStatus('idle'); return false; } try { const models = await validateGeminiKey(value); state.model = models.selected; state.textModel = models.selected; state.modelLimits = models.limits; state.apiKey = value; setConnectionStatus('connected', `Ativa · ${state.model}`); return true; } catch (error) { state.apiKey = null; state.model = null; state.textModel = null; state.modelLimits = { input: 32768, output: 8192 }; setConnectionStatus('error', error.message); if (!silent) showQuotaFallback(error.message); return false; } }
const storedKey = localStorage.getItem(KEY_STORAGE); const providerReady = (async () => { const candidates = [...new Set([storedKey, UNIVERSAL_KEY].filter(Boolean))]; if (!candidates.length) { setConnectionStatus('idle'); $('#modeTitle').textContent = 'Modo local'; $('#modeDescription').textContent = 'Nenhum provedor validado. Conecte uma chave para ativar a Brown.'; showProviderSetup(); return false; } $('#statusText').textContent = 'CONNECTING'; $('#modeTitle').textContent = 'Verificando conexão'; $('#modeDescription').textContent = 'A Brown está validando o provedor antes da primeira mensagem.'; for (const candidate of candidates) { if (await connectGemini(candidate, true)) { $('#channelMode').textContent = 'GEMINI'; hideProviderSetup(); return true; } } if (storedKey) localStorage.removeItem(KEY_STORAGE); $('#modeTitle').textContent = 'Modo local'; $('#modeDescription').textContent = 'O provedor não foi validado. Conecte uma chave para ativar a Brown.'; showProviderSetup('A conexão automática falhou. Insira uma chave para continuar.'); return false; })();


function clearPendingFile() { state.pendingFile = null; state.model = state.textModel || state.model; $('#fileInput').value = ''; $('#attachmentPreview').hidden = true; $('#attachmentPreview').innerHTML = ''; }
function showPendingFile(file) { $('#attachmentPreview').hidden = false; $('#attachmentPreview').innerHTML = `<span class="file-glyph">DOC</span><span>${escapeText(file.name)} · ${escapeText(file.mimeType || 'arquivo')}</span><button type="button" id="removeFile" aria-label="Remover anexo">×</button>`; $('#removeFile').addEventListener('click', clearPendingFile); }
$('#fileButton').addEventListener('click', () => $('#fileInput').click());
$('#fileInput').addEventListener('change', e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 20 * 1024 * 1024) { alert('O arquivo deve ter no máximo 20 MB.'); e.target.value = ''; return; } const reader = new FileReader(); reader.onload = () => { const dataUrl = String(reader.result); state.pendingFile = { name: file.name, mimeType: file.type || 'application/octet-stream', dataUrl, base64: dataUrl.split(',')[1] || '', size: file.size }; state.lastFile = state.pendingFile; saveLastFile(state.pendingFile); showPendingFile(state.pendingFile); }; reader.readAsDataURL(file); });
$('#messages').addEventListener('click', e => { const promptButton = e.target.closest('[data-prompt]'); if (promptButton) { $('#promptInput').value = promptButton.dataset.prompt; $('#promptInput').focus(); return; } handleMessageAction(e); });
$('#messages').addEventListener('scroll', () => { const quick = $('#scrollSettingsBtn'); if (quick) quick.hidden = $('#messages').scrollTop < 70; });
$('#scrollSettingsBtn').addEventListener('click', () => { openMenu(); const panel = $('#settingsPanel'); if (panel) { panel.hidden = false; syncSettingsPanel(); } });
$('#dismissNotice').addEventListener('click', () => $('#modeNotice').remove());
$('#clearBtn').addEventListener('click', () => { if (!state.messages.length || confirm(lang() === 'en' ? 'Clear current session?' : lang() === 'es' ? '¿Limpiar la sesión actual?' : 'Limpar a sessão atual?')) { state.messages = []; renderMessages(); } });
$('#exportBtn').addEventListener('click', () => { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), profile: state.profile, thinking: state.thinking, language: state.language, messages: state.messages }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `brown-ia-sessao-${Date.now()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); });
$('#settingsBtn').addEventListener('click', openMenu);
$('#composer').addEventListener('submit', async e => { e.preventDefault(); const input = $('#promptInput'); await Promise.all([fileReady, providerReady]); const content = input.value.trim(); if (!content && !state.pendingFile && !state.lastFile) return; const started = performance.now(); const file = state.pendingFile || state.lastFile; if (state.pendingFile) { state.lastFile = state.pendingFile; saveLastFile(state.lastFile); } const messageText = content || `Leia e explique o arquivo anexado: ${file?.name || ''}`; if (Number.isInteger(state.editingIndex)) { state.messages = state.messages.slice(0, state.editingIndex); state.editingIndex = null; } state.messages.push({ role: 'user', content: messageText, attachmentName: file?.name || '', at: new Date().toISOString() }); input.value = ''; clearPendingFile(); renderMessages(); $('#statusText').textContent = state.apiKey ? 'GEMINI PROCESSING' : 'PROCESSING'; $('#latencyLabel').textContent = 'processando'; try { const answer = state.apiKey ? await geminiReply(messageText, file) : await new Promise(resolve => setTimeout(() => resolve(localReply(content)), 120)); state.messages.push({ role: 'assistant', content: answer, at: new Date().toISOString() }); } catch (error) { const quotaError = /429|quota|rate limit|resource exhausted|limit exceeded/i.test(error.message); if (quotaError) showQuotaFallback(error.message); setConnectionStatus('error', quotaError ? 'Provedor temporariamente indisponível' : 'Falha no arquivo ou no provedor'); state.messages.push({ role: 'assistant', content: `Não foi possível processar a solicitação: ${error.message}`, at: new Date().toISOString() }); } renderMessages(); const ms = ((performance.now() - started) / 1000).toFixed(1); $('#statusText').textContent = state.apiKey ? 'GEMINI READY' : 'LOCAL READY'; $('#latencyLabel').textContent = `${ms}s · ${state.apiKey ? 'Gemini' : 'modo local'}`; });
$('#promptInput').addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); $('#composer').requestSubmit(); } });
setActive('.profile-btn','profile',state.profile); renderChatList(); renderProjects(); updateTags(); renderMessages();
