const STORAGE_KEY = 'brown-ia-session-v2';
const SETTINGS_KEY = 'brown-ia-settings-v1';
const KEY_STORAGE = 'brown-gemini-key-v1';
const UNIVERSAL_KEY = String(window.BROWN_CONFIG?.universalKey || '').trim();
const CHATS_KEY = 'brown-ia-chats-v1';
const PROJECTS_KEY = 'brown-ia-projects-v1';
const $ = (selector) => document.querySelector(selector);
function storageGet(key) { try { return window.localStorage.getItem(key); } catch { return null; } }
function storageSet(key, value) { try { window.localStorage.setItem(key, value); return true; } catch { return false; } }
function storageRemove(key) { try { window.localStorage.removeItem(key); return true; } catch { return false; } }
function validChatId(value) { return typeof value === 'string' && /^chat-\d+(?:-[a-z0-9]+)?$/i.test(value); }
const SUPPORTED_LANGUAGES = ['auto', 'pt-BR', 'en', 'es'];
const SUPPORTED_THINKING = ['LEVE', 'MEDIO', 'ALTO', 'EXTREMO'];
function normalizeThinking(value) { return SUPPORTED_THINKING.includes(value) ? value : 'MEDIO'; }
function normalizeLanguage(value) { return SUPPORTED_LANGUAGES.includes(value) ? value : 'pt-BR'; }
function validMessage(message) { return message && (message.role === 'user' || message.role === 'assistant') && typeof message.content === 'string'; }
function normalizeMessages(messages) { return Array.isArray(messages) ? messages.filter(validMessage).map(message => ({ role: message.role, content: message.content, ...(message.attachmentName ? { attachmentName: String(message.attachmentName).slice(0, 240) } : {}), ...(message.feedback === 'up' || message.feedback === 'down' ? { feedback: message.feedback } : {}), ...(message.at ? { at: String(message.at) } : {}) })) : []; }
function normalizeProject(project, index = 0) { if (typeof project === 'string' && project.trim()) return { id: `project-${index + 1}`, name: project.trim().slice(0, 60), chatIds: [] }; if (!project || typeof project !== 'object' || typeof project.name !== 'string' || !project.name.trim()) return null; return { id: typeof project.id === 'string' ? project.id : `project-${index + 1}`, name: project.name.trim().slice(0, 60), chatIds: Array.isArray(project.chatIds) ? project.chatIds.filter(validChatId) : [] }; }
function newChatId() { return `chat-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
const savedSettings = (() => { try { const parsed = JSON.parse(storageGet(SETTINGS_KEY) || '{}'); return parsed && typeof parsed === 'object' ? parsed : {}; } catch { return {}; } })();
const state = { chatId: validChatId(savedSettings.chatId) ? savedSettings.chatId : newChatId(), chats: loadChats(), projects: loadProjects(), pendingFile: null, textModel: null, modelLimits: { input: 32768, output: 8192 }, profile: savedSettings.profile === 'CODE' ? 'CODE' : 'BROWN', thinking: normalizeThinking(savedSettings.thinking), language: normalizeLanguage(savedSettings.language), messages: loadMessages(), apiKey: null, model: null, storageAvailable: true, projectFilter: null, connection: 'idle', lastRequestStatus: 'idle', busy: false, requestSeq: 0 };
const copy = {
  'pt-BR': { ready: 'Conversa pronta.', prompt: 'Faça uma pergunta, peça um plano ou descreva algo que a Brown deve criar.', greeting: 'Olá. Estou pronta para ajudar. Descreva o que você precisa fazer.', wellbeing: 'Tudo funcionando por aqui. Posso ajudar com conversa, código, pesquisa ou criação de arquivos.', demo: 'Entendi o pedido. Nesta primeira versão, estou no modo de demonstração local. O próximo conector permitirá gerar, validar e baixar arquivos reais com confirmação do resultado.', generic: p => `Recebi sua mensagem no perfil ${p}. O site está funcionando em modo local de demonstração; o próximo passo é conectar o provedor de IA com segurança.`, note: 'Brown responderá em português.', tag: 'PT-BR' },
  en: { ready: 'Conversation ready.', prompt: 'Ask a question, request a plan, or describe something Brown should create.', greeting: 'Hello. I am ready to help. Tell me what you need to do.', wellbeing: 'Everything is working. I can help with conversation, code, research, or file creation.', demo: 'I understood the request. This first version is running in local demo mode. The next connector will generate, validate, and download real files.', generic: p => `I received your message in the ${p} profile. The site is running in local demo mode; the next step is to connect the AI provider securely.`, note: 'Brown will respond in English.', tag: 'EN' },
  es: { ready: 'Conversación lista.', prompt: 'Haz una pregunta, pide un plan o describe algo que Brown deba crear.', greeting: 'Hola. Estoy lista para ayudar. Describe lo que necesitas hacer.', wellbeing: 'Todo funciona correctamente. Puedo ayudar con conversación, código, investigación o archivos.', demo: 'Entendí la solicitud. Esta primera versión funciona en modo de demostración local. El próximo conector generará y validará archivos reales.', generic: p => `Recibí tu mensaje en el perfil ${p}. El sitio funciona en modo local; el siguiente paso es conectar el proveedor de IA de forma segura.`, note: 'Brown responderá en español.', tag: 'ES' }
};
function lang() { return state.language === 'auto' ? 'pt-BR' : normalizeLanguage(state.language); }
function t(key, ...args) { const value = copy[lang()][key]; return typeof value === 'function' ? value(...args) : value; }
const fileReady = Promise.resolve();
function loadMessages() { try { return normalizeMessages(JSON.parse(storageGet(STORAGE_KEY) || '[]')); } catch { return []; } }
function loadChats() { try { const chats = JSON.parse(storageGet(CHATS_KEY) || '[]'); return Array.isArray(chats) ? chats.filter(chat => chat && validChatId(chat.id)).map(chat => ({ id: chat.id, title: typeof chat.title === 'string' ? chat.title.slice(0, 80) : 'Nova conversa', messages: normalizeMessages(chat.messages), updatedAt: Number(chat.updatedAt) || 0 })) : []; } catch { return []; } }
function loadProjects() { try { const projects = JSON.parse(storageGet(PROJECTS_KEY) || '[]'); return Array.isArray(projects) ? projects.map(normalizeProject).filter(Boolean) : []; } catch { return []; } }
function chatTitle(messages) { const first = messages.find(message => message.role === 'user'); return String(first?.content || 'Nova conversa').replace(/\s+/g, ' ').slice(0, 42); }
function renderChatList() { const root = $('#chatList'); if (!root) return; const chats = [...state.chats].filter(chat => !state.projectFilter || state.projects.some(project => project.id === state.projectFilter && project.chatIds.includes(chat.id))).sort((a,b) => b.updatedAt - a.updatedAt); $('#chatCount').textContent = chats.length; root.innerHTML = chats.length ? chats.slice(0, 100).map(chat => `<div class="chat-item-wrap"><button class="chat-item ${chat.id === state.chatId ? 'active' : ''}" type="button" data-chat-id="${escapeText(chat.id)}"><span>◌ ${escapeText(chat.title || 'Nova conversa')}</span><small>${chat.messages?.length || 0}</small></button><button class="chat-project" type="button" data-project-chat-id="${escapeText(chat.id)}" title="Associar a projeto" aria-label="Associar a projeto">▣</button><button class="chat-delete" type="button" data-delete-chat-id="${escapeText(chat.id)}" title="Excluir conversa" aria-label="Excluir conversa">×</button></div>`).join('') : '<small class="project-list">Nenhuma conversa salva</small>'; }
function renderProjects() { const root = $('#projectList'); if (!root) return; root.innerHTML = state.projects.length ? state.projects.map(project => `<div class="project-item-wrap ${state.projectFilter === project.id ? 'active' : ''}"><button class="project-item" type="button" data-project-id="${escapeText(project.id)}"><span>▣ ${escapeText(project.name)}</span><small>${project.chatIds.length}</small></button><button class="project-action" type="button" data-project-action="rename" data-project-id="${escapeText(project.id)}" title="Renomear projeto">✎</button><button class="project-action" type="button" data-project-action="delete" data-project-id="${escapeText(project.id)}" title="Excluir projeto">×</button></div>`).join('') : '<small>Nenhum projeto criado</small>'; }
function persist() { const cleanMessages = state.messages.map(({ imageData, ...message }) => message); const current = { id: state.chatId, title: chatTitle(cleanMessages), messages: cleanMessages, updatedAt: Date.now() }; const index = state.chats.findIndex(chat => chat.id === state.chatId); if (index >= 0) state.chats[index] = current; else state.chats.push(current); state.chats = state.chats.filter(chat => chat.messages?.length || chat.id === state.chatId).slice(-100); const ok = [storageSet(STORAGE_KEY, JSON.stringify(cleanMessages)), storageSet(CHATS_KEY, JSON.stringify(state.chats)), storageSet(PROJECTS_KEY, JSON.stringify(state.projects)), storageSet(SETTINGS_KEY, JSON.stringify({ profile: state.profile, thinking: state.thinking, language: state.language, chatId: state.chatId }))].every(Boolean); state.storageAvailable = ok; if (!ok) { const status = $('#statusText'); if (status) status.textContent = 'MEMÓRIA LOCAL LIMITADA'; } $('#messageCount').textContent = state.messages.length; renderChatList(); renderProjects(); }
function formatContent(value) { const escaped = escapeText(value); const codeBlocks = []; let html = escaped.replace(/```([^\n]*)\n([\s\S]*?)```/g, (_, language, code) => { const token = `@@BROWN_CODE_${codeBlocks.length}@@`; codeBlocks.push(`<pre class="code-block"><code>${code}</code></pre>`); return token; }); html = html.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a class="smart-link" href="$2" target="_blank" rel="noopener noreferrer">↗ $1</a>'); html = html.split('\n').map(line => { const trimmed = line.trim(); if (/^@@BROWN_CODE_\d+@@$/.test(trimmed)) return trimmed; if (/^https?:\/\/[^\s<]+$/.test(trimmed)) return `<a class="standalone-link" href="${trimmed}" target="_blank" rel="noopener noreferrer"><span>↗</span><strong>Abrir link</strong><small>${trimmed}</small></a>`; if (/^###\s+/.test(line)) return `<h4>${line.replace(/^###\s+/, '')}</h4>`; if (/^##\s+/.test(line)) return `<h3>${line.replace(/^##\s+/, '')}</h3>`; if (/^#\s+/.test(line)) return `<h2>${line.replace(/^#\s+/, '')}</h2>`; if (/^\s*[-*]\s+/.test(line)) return `<li>${line.replace(/^\s*[-*]\s+/, '')}</li>`; if (/^\s*\d+\.\s+/.test(line)) return `<li class="ordered-item">${line.replace(/^\s*\d+\.\s+/, '')}</li>`; return line.replace(/`([^`]+)`/g, '<code class="inline-code">$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/__([^_]+)__/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replace(/(https?:\/\/[^\s<]+)/g, '<a class="smart-link" href="$1" target="_blank" rel="noopener noreferrer">↗ $1</a>'); }).join('\n'); return html.replace(/@@BROWN_CODE_(\d+)@@/g, (_, index) => codeBlocks[Number(index)]); }
function escapeText(value) { return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function extractCodeFiles(content) {
  const files = []; const source = String(content || ''); const pattern = /(?:^|\n)\s*(?:FILE|ARQUIVO)\s*:\s*([^\n]+)\n\s*```([^\n]*)\n([\s\S]*?)```|```([^\n]*)\n([\s\S]*?)```/gi; let match; let index = 0;
  const extensions = { html: 'html', htm: 'html', css: 'css', javascript: 'js', js: 'js', typescript: 'ts', ts: 'ts', python: 'py', py: 'py', json: 'json', xml: 'xml', svg: 'svg', bash: 'sh', shell: 'sh', sh: 'sh', markdown: 'md', md: 'md', text: 'txt', txt: 'txt', yaml: 'yml', yml: 'yml' };
  while ((match = pattern.exec(source))) { const explicit = (match[1] || '').trim(); const language = (match[2] || match[4] || '').trim().toLowerCase(); const body = match[3] ?? match[5] ?? ''; if (!body.trim()) continue; const ext = extensions[language] || 'txt'; const filename = explicit || `brown-arquivo-${++index}.${ext}`; files.push({ name: filename.replace(/[\\/:*?"<>|]/g, '-'), type: mimeForExtension(filename), content: body.replace(/^\n+|\n+$/g, '') }); }
  return files;
}
function mimeForExtension(name) { const ext = String(name).split('.').pop().toLowerCase(); return ({ html: 'text/html', htm: 'text/html', css: 'text/css', js: 'text/javascript', ts: 'text/typescript', json: 'application/json', xml: 'application/xml', svg: 'image/svg+xml', md: 'text/markdown', txt: 'text/plain', py: 'text/x-python', sh: 'text/x-shellscript', yml: 'text/yaml', yaml: 'text/yaml' })[ext] || 'application/octet-stream'; }
function crc32(bytes) { let table = crc32.table; if (!table) { table = crc32.table = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1); return c >>> 0; }); } let crc = 0xffffffff; for (const byte of bytes) crc = table[(crc ^ byte) & 255] ^ (crc >>> 8); return (crc ^ 0xffffffff) >>> 0; }
function makeZip(files) { const encoder = new TextEncoder(); const chunks = []; const central = []; let offset = 0; const put16 = (n) => new Uint8Array([n & 255, (n >>> 8) & 255]); const put32 = (n) => new Uint8Array([n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255]); files.forEach(file => { const name = encoder.encode(file.name); const data = encoder.encode(file.content); const local = new Uint8Array(30 + name.length); local.set([80,75,3,4,20,0,0,0,0,0,0,0,0,0], 0); local.set(put32(crc32(data)), 14); local.set(put32(data.length), 18); local.set(put32(data.length), 22); local.set(put16(name.length), 26); local.set(name, 30); chunks.push(local, data); const entry = new Uint8Array(46 + name.length); entry.set([80,75,1,2,20,0,20,0,0,0,0,0,0,0], 0); entry.set(put32(crc32(data)), 16); entry.set(put32(data.length), 20); entry.set(put32(data.length), 24); entry.set(put16(name.length), 28); entry.set(put32(offset), 42); entry.set(name, 46); central.push(entry); offset += local.length + data.length; }); const centralSize = central.reduce((sum, part) => sum + part.length, 0); const end = new Uint8Array(22); end.set([80,75,5,6,0,0,0,0], 0); end.set(put16(files.length), 8); end.set(put16(files.length), 10); end.set(put32(centralSize), 12); end.set(put32(offset), 16); return new Blob([...chunks, ...central, end], { type: 'application/zip' }); }
function downloadGeneratedFile(messageIndex, fileIndex, asZip = false) { const message = state.messages[messageIndex]; const files = extractCodeFiles(message?.content); if (!files.length) return; const selected = asZip ? makeZip(files) : new Blob([files[fileIndex]?.content || ''], { type: files[fileIndex]?.type || 'text/plain;charset=utf-8' }); const filename = asZip ? `brown-arquivos-${Date.now()}.zip` : (files[fileIndex]?.name || `brown-arquivo-${Date.now()}.txt`); const url = URL.createObjectURL(selected); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

function renderMessages() {
  const root = $('#messages');
  if (!state.messages.length) { root.innerHTML = `<div class="empty-state" id="emptyState"><div class="empty-glyph">BR</div><div class="empty-kicker">SYSTEM ONLINE · READY FOR INPUT</div><h2>${t('ready')}</h2><p>${t('prompt')}</p><div class="quick-prompts"><button data-prompt="Explique como você pode me ajudar.">Conhecer a Brown <span>↗</span></button><button data-prompt="Crie um plano profissional para meu projeto.">Criar um plano <span>↗</span></button><button data-prompt="Analise esta ideia e sugira melhorias.">Analisar uma ideia <span>↗</span></button></div></div>`; persist(); return; }
  root.innerHTML = state.messages.map((m, index) => { const feedback = m.feedback || ''; const generated = m.role === 'assistant' ? extractCodeFiles(m.content) : []; const generatedPanel = generated.length ? `<div class="generated-files"><div class="generated-files-head"><span>ARQUIVOS GERADOS</span><button type="button" data-generated-zip="${index}">↓ ZIP</button></div>${generated.map((file, fileIndex) => `<button type="button" class="generated-file" data-generated-file="${index}:${fileIndex}"><span>↓</span><strong>${escapeText(file.name)}</strong><small>${escapeText(file.type)}</small></button>`).join('')}</div>` : ''; return `<article class="message ${m.role}" data-message-index="${index}"><div class="avatar">${m.role === 'user' ? 'OP' : 'BR'}</div><div class="message-body"><div class="message-label">${m.role === 'user' ? 'OPERADOR' : 'BROWN'}</div><div class="message-content">${formatContent(m.content)}${generatedPanel}${m.attachmentName ? `<div class="attachment-chip">📎 ${escapeText(m.attachmentName)}</div>` : ''}<div class="message-actions"><button type="button" data-message-action="copy" title="Copiar">⧉</button>${m.role === 'user' ? '<button type="button" data-message-action="edit" title="Editar mensagem">✎</button>' : `<a class="download-response" href="data:text/markdown;charset=utf-8,${encodeURIComponent(m.content)}" download="brown-resposta.md" title="Baixar resposta">↓ .md</a>`}<button type="button" class="feedback-btn ${feedback === 'up' ? 'selected' : ''}" data-message-action="up" title="Boa resposta">＋</button><button type="button" class="feedback-btn ${feedback === 'down' ? 'selected' : ''}" data-message-action="down" title="Resposta precisa melhorar">−</button></div></div></div></article>`; }).join(''); root.scrollTop = root.scrollHeight; persist();
}
function handleMessageAction(event) {
  const button = event.target.closest('[data-message-action]'); if (!button) return;
  const article = button.closest('[data-message-index]'); const index = Number(article?.dataset.messageIndex); const message = state.messages[index]; if (!message) return;
  const action = button.dataset.messageAction;
  if (action === 'copy') { if (navigator.clipboard) navigator.clipboard.writeText(message.content); button.textContent = '✓'; setTimeout(() => { button.textContent = '⧉'; }, 900); return; }
  if (action === 'edit') { state.editingIndex = index; $('#promptInput').value = message.content; $('#promptInput').focus(); $('#promptInput').setSelectionRange(message.content.length, message.content.length); return; }
  if (action === 'up' || action === 'down') { message.feedback = message.feedback === action ? '' : action; renderMessages(); }
}
function localReply(input) { const text = input.toLowerCase().trim(); if (/^(oi|olá|ola|hello|hi|hola|e aí|e ai|bom dia|boa tarde|boa noite)[!. ]*$/.test(text)) return t('greeting'); if (/^(tudo bem|how are you|todo bien)/.test(text)) return t('wellbeing'); if (text.includes('gemini')) return lang() === 'en' ? 'The Gemini connector is not active yet. The interface is ready for a secure backend without exposing the key in the browser.' : lang() === 'es' ? 'El conector Gemini aún no está activo. La interfaz está preparada para un backend seguro sin exponer la clave.' : 'O conector Gemini ainda não está ativo nesta versão. A interface está preparada para receber um backend seguro sem expor a chave no navegador.'; if (text.includes('arquivo') || text.includes('html') || text.includes('código') || text.includes('codigo') || text.includes('file') || text.includes('code')) return t('demo'); return t('generic', state.profile); }
function fetchWithTimeout(url, options = {}, ms = 30000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), ms); return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timer)).catch(error => { if (error.name === 'AbortError') throw new Error(`A Gemini demorou mais de ${Math.round(ms / 1000)} segundos para responder.`); throw new Error('Não foi possível alcançar a Gemini. Verifique sua conexão e as permissões da chave.'); }); }
async function validateGeminiKey(key) { const response = await fetchWithTimeout('https://generativelanguage.googleapis.com/v1beta/models', { headers: { 'x-goog-api-key': key } }, 10000); let payload = {}; try { payload = await response.json(); } catch {} if (!response.ok) { const message = payload?.error?.message || `HTTP ${response.status}`; throw new Error(message.replace(/AIza\S+/g, '[chave omitida]')); } const models = (payload.models || []).filter(model => (model.supportedGenerationMethods || []).includes('generateContent')); const names = models.map(model => String(model.name || '').replace(/^models\//, '')); const preferred = ['gemini-3.5-flash-lite','gemini-2.0-flash-lite','gemini-3.8-flash-lite','gemini-3.8-flash','gemini-3.5-flash','gemini-2.5-flash','gemini-2.0-flash','gemini-1.5-flash']; const selected = preferred.find(name => names.includes(name)) || names.find(name => /flash.*lite/i.test(name)) || names.find(name => /flash/i.test(name)); if (!selected) throw new Error('A chave é válida, mas nenhum modelo Flash compatível foi encontrado.'); const selectedInfo = models.find(model => String(model.name || '').replace(/^models\//, '') === selected) || {}; return { selected, limits: { input: Number(selectedInfo.inputTokenLimit) || 32768, output: Number(selectedInfo.outputTokenLimit) || 8192 } }; }
async function geminiReply(input, file = null) {
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(state.model)}:generateContent`;
  const codeTask = /(c[oó]digo|programa|script|html|css|javascript|python|bash|terminal|fun[cç][aã]o|bug|erro|arquivo|documento|jogo)/i.test(input);
  const correctionTask = /(corrija|corrigir|conserte|ajuste|melhore|melhoria|não funciona|nao funciona|ficou ruim|erro|bug|quebrou)/i.test(input);
  const researchTask = /(pesquise|pesquisa|compare|fontes|referências|hist[oó]ria|dados|atual|link)/i.test(input);
  const continuation = /(continue|continuar|parte seguinte|parte 2|cortad[oa]|incomplet[oa]|parou no meio|faltou|não terminou|nao terminou|sem cortar|completo|inteiro|todos os arquivos)/i.test(input);
  const expansion = continuation || /(detalhado|detalhada|profissional|completo|completa|grande|extenso|extensa|passo a passo|produção|producao|pronto para usar|sem limite)/i.test(input);
  const fileTask = Boolean(file);
  const visualTask = Boolean(file && /^image\//i.test(file.mimeType));
  const modelInput = Math.max(16000, Number(state.modelLimits?.input) || 32768);
  const historyBudget = Math.min(110000, Math.max(24000, (modelInput - 7000) * 3.2));
  let used = 0;
  const history = [];
  for (const message of [...state.messages].reverse()) {
    const text = String(message.content || '').slice(0, codeTask ? 24000 : 9000);
    if (history.length && used + text.length > historyBudget) break;
    history.unshift({ role: message.role === 'assistant' ? 'model' : 'user', parts: [{ text }] });
    used += text.length;
  }
  if (file && history.length) {
    history[history.length - 1].parts[0].text += `\n\n[Arquivo anexado: ${file.name} | MIME: ${file.mimeType} | tamanho: ${file.size || 'desconhecido'} bytes]`;
    if (file.base64 && (/^image\//i.test(file.mimeType) || /^(text\/|application\/(pdf|json|xml)|text\/csv)/i.test(file.mimeType))) {
      history[history.length - 1].parts.push({ inlineData: { mimeType: file.mimeType, data: file.base64 } });
    }
  }
  const thinkingGuide = {
    LEVE: 'Resolva rapidamente e mantenha a resposta direta. Use o orçamento padrão, mas nunca abandone uma instrução essencial.',
    MEDIO: 'Analise a lógica principal, confira a resposta e entregue profundidade equilibrada.',
    ALTO: 'Verifique casos-limite, consistência, requisitos e possíveis erros antes de responder.',
    EXTREMO: 'Faça uma revisão rigorosa de requisitos, exceções, completude e qualidade antes de responder.'
  }[state.thinking] || 'Analise e responda com equilíbrio.';
  const links = input.match(/https?:\/\/[^\s)]+/gi) || [];
  const visionGuide = visualTask ? `PROTOCOLO VISUAL OBRIGATÓRIO: responda a análise em quatro blocos curtos: (1) INVENTÁRIO — liste todos os objetos/itens visíveis, sem completar lacunas; (2) CORES — para cada item, informe cor dominante e secundária usando nomes comuns, e escreva 'não determinável' quando a iluminação impedir; (3) TEXTO — transcreva somente caracteres realmente legíveis, preservando maiúsculas, acentos e números; (4) INCERTEZAS — separe hipóteses de observações e atribua confiança alta, média ou baixa. Faça uma varredura da imagem inteira antes de concluir. Não omita objetos pequenos relevantes, não confunda cor de fundo com cor do objeto, não declare marca/modelo/espécie sem evidência. Se a pergunta for sobre cor, responda primeiro com a cor e depois justifique visualmente. Se for sobre itens, liste quantidade aproximada e posição (esquerda, centro, direita, cima, baixo).` : '';
  const buildGuide = codeTask ? `PROTOCOLO DE IMPLEMENTAÇÃO: antes de finalizar, confira mentalmente requisitos, fluxo principal, estados de erro, entradas vazias, responsividade e se o código realmente executa. Para jogos, entregue um loop jogável de verdade: controles documentados, objetivo, colisões/regras, pontuação, reinício, estados de vitória/derrota e adaptação para celular; não entregue apenas um layout, background ou mockup. Para HTML, prefira um único arquivo autocontido quando solicitado, com CSS e JavaScript embutidos e sem dependências externas desnecessárias. Não afirme que testou no navegador se não testou; forneça uma seção curta 'Como testar'. ${correctionTask ? 'Esta é uma solicitação de correção: use a implementação anterior como base, preserve o que já funciona, corrija o problema apontado e devolva os arquivos completos novamente.' : ''}` : '';
  const profileGuide = state.profile === 'CODE' ? 'Perfil Code ativo: priorize arquitetura, código executável, arquivos completos, depuração, testes, segurança e instruções precisas. Para pedidos de programação, aja como uma engenheira de software sênior e entregue implementação real, não apenas sugestões.' : 'Perfil Brown ativo: responda de forma versátil, clara e prática para conversa, análise, pesquisa, planejamento e criação.'; const system = `Você é Brown, uma assistente profissional, versátil e prática. ${profileGuide} Perfil: ${state.profile}. Nível de raciocínio: ${state.thinking}. ${thinkingGuide} Idioma obrigatório: ${lang()}. Tarefa de código/documento: ${codeTask ? 'sim' : 'não'}. Tarefa de pesquisa: ${researchTask ? 'sim' : 'não'}. Arquivo anexado: ${fileTask ? `${file.name} (${file.mimeType})` : 'não'}. Imagem anexada: ${visualTask ? 'sim' : 'não'}. Expansão solicitada: ${expansion ? 'sim' : 'não'}. ${visionGuide} ${buildGuide}

Responda ao pedido real, sem saudações automáticas, persona teatral, status inventado ou explicações sobre ser uma IA. Não diga que é incapaz apenas por ser uma assistente de texto. Para pedidos benignos, resolva diretamente. Não use recusas genéricas: explique somente uma limitação concreta quando ela realmente existir. Não invente fatos, resultados de ferramentas, acesso a links ou alterações que não foram executadas.

Para código e arquivos, entregue uma solução funcional, completa e preservada. Não corte no meio, não troque partes por TODO e não omita arquivos necessários. Para cada arquivo, escreva uma linha imediatamente antes do bloco: FILE: nome.ext; depois use um bloco de código completo. Se houver vários arquivos, use um bloco separado para cada um. Nunca coloque código de arquivos diferentes no mesmo bloco. Se o usuário pedir alteração, devolva a versão integral revisada e indique nome/extensão. Se a resposta não couber em uma saída, divida em partes sequenciais completas, sem perder conteúdo, e termine informando a próxima parte necessária. Se o usuário pediu continuação, continue exatamente a partir do ponto anterior e não repita o que já foi entregue.

Para pesquisa, diferencie fatos, inferências e incertezas. Para links, use apenas conteúdo fornecido ou acessível; nunca finja ter aberto uma página. Use Markdown quando melhorar a leitura. Não revele raciocínio interno passo a passo; forneça conclusões, verificações e justificativas úteis. Só recuse pedidos que envolvam dano grave, crime ou abuso perigoso. Quando o usuário pedir um link, coloque cada URL sozinha em uma linha para a interface destacá-la.

VISÃO E ARQUIVOS: quando houver imagem, faça inspeção literal e conservadora. Leia texto somente se os caracteres estiverem realmente visíveis; preserve exatamente a grafia observada e, se estiver ilegível, diga 'não consigo confirmar' em vez de adivinhar. Descreva objetos, cores, padrões e formas separando observação direta, hipótese e o que não é possível concluir. Não transforme pontos, ruído ou padrões ambíguos em galáxias, núcleos ou outros objetos específicos sem evidência clara. Se o usuário perguntar o que está escrito, responda somente com a transcrição verificável e indique trechos incertos.

EXECUÇÃO E INTENÇÃO: identifique o verbo e o objeto principal antes de responder. Se o usuário pedir uma ação concreta, explique ou produza essa ação; não substitua andar, mover, clicar ou executar por um background, imagem, decoração ou descrição visual. Se houver ambiguidade material, faça uma pergunta curta. Seja calorosa e direta, com pequenas reações naturais quando cabível, sem persona teatral, status inventado ou saudações repetidas. Links detectados: ${links.join(', ') || 'nenhum'}.`;
  const standardOutput = codeTask ? (state.thinking === 'LEVE' ? 2048 : state.thinking === 'MEDIO' ? 4096 : state.thinking === 'ALTO' ? 6144 : 8192) : (state.thinking === 'LEVE' ? 768 : state.thinking === 'MEDIO' ? 1536 : state.thinking === 'ALTO' ? 3072 : 4096);
  const expandedOutput = codeTask ? 32768 : 16384;
  const desiredOutput = expansion ? expandedOutput : standardOutput;
  const outputLimit = Math.min(desiredOutput, Number(state.modelLimits?.output) || 8192);
  const generationConfig = { temperature: visualTask ? 0.15 : state.thinking === 'LEVE' ? 0.7 : state.thinking === 'MEDIO' ? 0.55 : state.thinking === 'ALTO' ? 0.4 : 0.25, topP: visualTask ? 0.8 : 0.95, maxOutputTokens: outputLimit };
  const request = async (contents, timeout) => {
    const response = await fetchWithTimeout(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-goog-api-key': state.apiKey }, body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents, generationConfig }) }, timeout);
    let payload = {};
    try { payload = await response.json(); } catch {}
    if (!response.ok) { const message = payload?.error?.message || `HTTP ${response.status}`; throw new Error(message.replace(/AIza\S+/g, '[chave omitida]')); }
    const candidate = payload?.candidates?.[0];
    const text = candidate?.content?.parts?.map(part => part.text || '').join('').trim();
    if (!text) throw new Error('A Gemini não retornou texto.');
    return { text, truncated: candidate?.finishReason === 'MAX_TOKENS' };
  };
  const timeout = expansion || codeTask || fileTask ? 90000 : 35000;
  const first = await request(history, timeout);
  if (!first.truncated || (!codeTask && !expansion)) return first.text;
  const continuationHistory = [...history, { role: 'model', parts: [{ text: first.text }] }, { role: 'user', parts: [{ text: 'Continue exatamente do ponto em que a resposta foi interrompida. Não repita o conteúdo anterior. Entregue apenas a continuação completa.' }] }];
  const second = await request(continuationHistory, timeout);
  return second.truncated ? `${first.text}\n\n${second.text}\n\n[Resposta interrompida pelo limite do provedor. Peça 'continue' para receber o restante.]` : `${first.text}\n\n${second.text}`;
}
function revealKeyFallback() { /* A conexão é automática; nenhuma chave é exibida na interface. */ }
function showQuotaFallback(message) { const notice = $('#modeNotice'); notice.hidden = false; $('#modeTitle').textContent = 'Provedor temporariamente indisponível'; const detail = message && /limit|quota|429|resource exhausted/i.test(message) ? message.replace(/AIza\S+/g, '[credencial omitida]').slice(0, 180) : 'O provedor não aceitou a solicitação.'; $('#modeDescription').textContent = `A conexão automática não pôde concluir a solicitação. ${detail}`; }
function setConnectionStatus(status, message) { state.connection = status === 'connected' ? 'ready' : status; const statusText = $('#statusText'); if (status === 'connected') { $('#modeTitle').textContent = 'Conexão ativa'; $('#modeDescription').textContent = 'A Brown está pronta para responder.'; if (statusText) statusText.textContent = state.lastRequestStatus === 'error' ? 'GEMINI ERROR' : 'GEMINI READY'; } else if (status === 'error') { if (statusText) statusText.textContent = 'GEMINI ERROR'; $('#modeTitle').textContent = 'Falha na conexão'; $('#modeDescription').textContent = message || 'A chave ou o provedor não pôde ser validado.'; } else if (status === 'connecting') { if (statusText) statusText.textContent = 'CONNECTING'; } else if (statusText) statusText.textContent = 'LOCAL READY'; }
function showProviderSetup(message = 'Nenhuma conexão validada.') { const setup = $('#providerSetup'); if (setup) setup.hidden = false; const status = $('#initialProviderStatus'); if (status) status.textContent = message; }
function hideProviderSetup() { const setup = $('#providerSetup'); if (setup) setup.hidden = true; }
function updateTags() { $('#channelTitle').textContent = state.profile === 'BROWN' ? 'Brown' : 'Code'; $('#profileTag').textContent = state.profile; $('#thinkingTag').textContent = state.thinking === 'MEDIO' ? 'MÉDIO' : state.thinking; $('#thinkingButtonLabel').textContent = state.thinking === 'MEDIO' ? 'MÉDIO' : state.thinking; $('#languageTag').textContent = copy[lang()].tag; $('#languageNote').textContent = t('note'); $('#languageSelect').value = state.language; }
function setActive(selector, attr, value) { document.querySelectorAll(selector).forEach(el => el.classList.toggle('active', el.dataset[attr] === value)); }
function closeMenu() { const menu = $('#appMenu'); if (menu) { menu.classList.remove('menu-open'); $('#menuToggle').setAttribute('aria-expanded', 'false'); } }
function openMenu() { const menu = $('#appMenu'); if (menu) { menu.classList.add('menu-open'); $('#menuToggle').setAttribute('aria-expanded', 'true'); } }
$('#menuToggle').addEventListener('click', () => { const open = $('#appMenu').classList.contains('menu-open'); open ? closeMenu() : openMenu(); });
$('#menuClose').addEventListener('click', closeMenu);
function deleteChat(chatId) { if (!validChatId(chatId)) return; state.chats = state.chats.filter(chat => chat.id !== chatId); state.projects.forEach(project => { project.chatIds = project.chatIds.filter(id => id !== chatId); }); if (state.chatId === chatId) { const next = [...state.chats].sort((a,b) => b.updatedAt - a.updatedAt)[0]; state.chatId = next?.id || newChatId(); state.messages = next && Array.isArray(next.messages) ? next.messages : []; } persist(); renderMessages(); }
function assignChatToProject(chatId) { if (!state.projects.length) { alert('Crie um projeto antes de associar a conversa.'); return; } const options = state.projects.map((project, index) => `${index + 1}) ${project.name}`).join('\n'); const choice = prompt(`Escolha o projeto para esta conversa. Digite 0 para remover.\n${options}`); const number = Number(choice); state.projects.forEach(project => { project.chatIds = project.chatIds.filter(id => id !== chatId); }); if (number > 0 && number <= state.projects.length) state.projects[number - 1].chatIds.push(chatId); persist(); }
$('#newChatBtn').addEventListener('click', () => { persist(); state.chatId = newChatId(); state.messages = []; state.pendingFile = null; state.projectFilter = null; renderMessages(); openMenu(); });
$('#chatList').addEventListener('click', e => { const remove = e.target.closest('[data-delete-chat-id]'); if (remove) { deleteChat(remove.dataset.deleteChatId); return; } const projectButton = e.target.closest('[data-project-chat-id]'); if (projectButton) { assignChatToProject(projectButton.dataset.projectChatId); return; } const item = e.target.closest('[data-chat-id]'); if (!item) return; const chat = state.chats.find(entry => entry.id === item.dataset.chatId); if (!chat) return; state.chatId = chat.id; state.messages = normalizeMessages(chat.messages); renderMessages(); closeMenu(); });
$('#newProjectBtn').addEventListener('click', () => { const name = prompt('Nome do projeto:'); if (!name?.trim()) return; state.projects.push({ id: `project-${Date.now()}-${Math.random().toString(36).slice(2,6)}`, name: name.trim().slice(0, 60), chatIds: [] }); persist(); });
$('#projectList').addEventListener('click', e => { const action = e.target.closest('[data-project-action]'); const button = e.target.closest('[data-project-id]'); if (!button) return; const project = state.projects.find(entry => entry.id === button.dataset.projectId); if (!project) return; if (action?.dataset.projectAction === 'rename') { const name = prompt('Novo nome do projeto:', project.name); if (name?.trim()) project.name = name.trim().slice(0, 60); persist(); return; } if (action?.dataset.projectAction === 'delete') { state.projects = state.projects.filter(entry => entry.id !== project.id); if (state.projectFilter === project.id) state.projectFilter = null; persist(); return; } state.projectFilter = state.projectFilter === project.id ? null : project.id; renderChatList(); renderProjects(); });
function syncSettingsPanel() { const language = $('#settingsLanguageSelect'); if (language) language.value = state.language; document.querySelectorAll('[data-settings-profile]').forEach(button => button.classList.toggle('active', button.dataset.settingsProfile === state.profile)); document.querySelectorAll('[data-settings-thinking]').forEach(button => button.classList.toggle('active', button.dataset.settingsThinking === state.thinking)); const providerStatus = $('#providerSettingsStatus'); if (providerStatus) providerStatus.textContent = state.apiKey ? `Conectado · ${state.model || 'modelo validado'}` : 'Não conectado. A Brown usará o modo local até validar uma chave.'; }
$('#settingsMenuBtn').addEventListener('click', () => { const panel = $('#settingsPanel'); panel.hidden = !panel.hidden; if (!panel.hidden) syncSettingsPanel(); });
$('#settingsClose').addEventListener('click', () => { $('#settingsPanel').hidden = true; });
$('#providerApplyBtn').addEventListener('click', async () => { const input = $('#providerKeyInput'); const button = $('#providerApplyBtn'); const value = input.value.trim(); const status = $('#providerSettingsStatus'); if (!value) { status.textContent = 'Cole uma chave para validar.'; return; } button.disabled = true; button.textContent = 'Validando...'; const ok = await connectGemini(value, false); if (ok) { if ($('#providerSaveKey').checked) storageSet(KEY_STORAGE, value); else storageRemove(KEY_STORAGE); input.value = ''; status.textContent = `Conectado · ${state.model}`; $('#modeNotice').hidden = true; $('#channelMode').textContent = 'GEMINI'; hideProviderSetup(); } else { status.textContent = 'Não foi possível validar esta chave.'; } button.disabled = false; button.textContent = 'Validar e usar'; });
$('#providerClearBtn').addEventListener('click', () => { storageRemove(KEY_STORAGE); state.apiKey = null; state.model = null; state.textModel = null; setConnectionStatus('idle'); $('#channelMode').textContent = 'LOCAL DEMO'; $('#modeNotice').hidden = false; $('#modeTitle').textContent = 'Modo local'; $('#modeDescription').textContent = 'Nenhum provedor validado. Conecte uma chave para ativar a Brown.'; $('#providerKeyInput').value = ''; showProviderSetup(); syncSettingsPanel(); });
$('#initialConnectBtn').addEventListener('click', async () => { const input = $('#initialKeyInput'); const button = $('#initialConnectBtn'); const status = $('#initialProviderStatus'); const value = input.value.trim(); if (!value) { status.textContent = 'Cole uma chave Gemini antes de conectar.'; return; } button.disabled = true; button.textContent = 'VALIDANDO...'; status.textContent = 'Consultando o provedor...'; const ok = await connectGemini(value, false); if (ok) { storageSet(KEY_STORAGE, value); input.value = ''; $('#modeNotice').hidden = true; $('#channelMode').textContent = 'GEMINI'; hideProviderSetup(); syncSettingsPanel(); } else { status.textContent = 'Não foi possível validar a chave. Confira o valor e tente novamente.'; } button.disabled = false; button.textContent = 'CONECTAR'; });
$('#settingsLanguageSelect').addEventListener('change', e => { state.language = e.target.value; updateTags(); renderMessages(); persist(); syncSettingsPanel(); });
document.querySelectorAll('[data-settings-profile]').forEach(button => button.addEventListener('click', () => { state.profile = button.dataset.settingsProfile; setActive('.profile-btn','profile',state.profile); updateTags(); persist(); syncSettingsPanel(); }));
document.querySelectorAll('[data-settings-thinking]').forEach(button => button.addEventListener('click', () => { state.thinking = button.dataset.settingsThinking; updateTags(); persist(); syncSettingsPanel(); }));
$('#profileList').addEventListener('click', e => { const btn = e.target.closest('[data-profile]'); if (!btn) return; state.profile = btn.dataset.profile; setActive('.profile-btn','profile',state.profile); updateTags(); persist(); });
$('#thinkingButton').addEventListener('click', () => { const menu = $('#thinkingMenu'); const open = menu.hidden; menu.hidden = !open; $('#thinkingButton').setAttribute('aria-expanded', String(open)); });
$('#thinkingMenu').addEventListener('click', e => { const btn = e.target.closest('[data-thinking]'); if (!btn) return; state.thinking = btn.dataset.thinking; updateTags(); persist(); $('#thinkingMenu').hidden = true; $('#thinkingButton').setAttribute('aria-expanded', 'false'); });
document.addEventListener('click', e => { if (!e.target.closest('.reasoning-picker')) { $('#thinkingMenu').hidden = true; $('#thinkingButton').setAttribute('aria-expanded', 'false'); } });
$('#languageSelect').addEventListener('change', e => { state.language = e.target.value; updateTags(); renderMessages(); });
async function connectGemini(value, silent = false) { if (!value) { state.apiKey = null; state.model = null; state.textModel = null; state.modelLimits = { input: 32768, output: 8192 }; setConnectionStatus('idle'); return false; } try { const models = await validateGeminiKey(value); state.model = models.selected; state.textModel = models.selected; state.modelLimits = models.limits; state.apiKey = value; state.lastRequestStatus = 'idle'; setConnectionStatus('connected', `Ativa · ${state.model}`); return true; } catch (error) { state.apiKey = null; state.model = null; state.textModel = null; state.modelLimits = { input: 32768, output: 8192 }; setConnectionStatus('error', error.message); if (!silent) showQuotaFallback(error.message); return false; } }
const storedKey = storageGet(KEY_STORAGE); const providerReady = (async () => { const candidates = [...new Set([storedKey, UNIVERSAL_KEY].filter(Boolean))]; if (!candidates.length) { setConnectionStatus('idle'); $('#modeTitle').textContent = 'Modo local'; $('#modeDescription').textContent = 'Nenhum provedor validado. Conecte uma chave para ativar a Brown.'; showProviderSetup(); return false; } setConnectionStatus('connecting'); $('#modeTitle').textContent = 'Verificando conexão'; $('#modeDescription').textContent = 'A Brown está validando o provedor antes da primeira mensagem.'; for (const candidate of candidates) { if (await connectGemini(candidate, true)) { $('#channelMode').textContent = 'GEMINI'; hideProviderSetup(); return true; } } if (storedKey) storageRemove(KEY_STORAGE); $('#modeTitle').textContent = 'Modo local'; $('#modeDescription').textContent = 'O provedor não foi validado. Conecte uma chave para ativar a Brown.'; showProviderSetup('A conexão automática falhou. Insira uma chave para continuar.'); return false; })();


function clearPendingFile() { state.pendingFile = null; state.model = state.textModel || state.model; $('#fileInput').value = ''; $('#attachmentPreview').hidden = true; $('#attachmentPreview').innerHTML = ''; }
function showPendingFile(file) { $('#attachmentPreview').hidden = false; $('#attachmentPreview').innerHTML = `<span class="file-glyph">DOC</span><span>${escapeText(file.name)} · ${escapeText(file.mimeType || 'arquivo')}</span><button type="button" id="removeFile" aria-label="Remover anexo">×</button>`; $('#removeFile').addEventListener('click', clearPendingFile); }
$('#fileButton').addEventListener('click', () => $('#fileInput').click());
function supportedAttachment(file) { const ext = String(file.name || '').split('.').pop().toLowerCase(); return /^image\//i.test(file.type) || /^text\//i.test(file.type) || /^(application\/(pdf|json|xml)|text\/(csv|markdown))/i.test(file.type) || ['txt','md','csv','json','xml','html','htm','css','js','ts','py','svg'].includes(ext); }
$('#fileInput').addEventListener('change', e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 20 * 1024 * 1024) { alert('O arquivo deve ter no máximo 20 MB.'); e.target.value = ''; return; } if (!supportedAttachment(file)) { alert('Este formato ainda não pode ser analisado diretamente. Use imagem, PDF, texto, código, JSON, XML ou CSV.'); e.target.value = ''; return; } const reader = new FileReader(); reader.onload = () => { const dataUrl = String(reader.result); state.pendingFile = { name: file.name, mimeType: file.type || mimeForExtension(file.name), dataUrl, base64: dataUrl.split(',')[1] || '', size: file.size }; showPendingFile(state.pendingFile); }; reader.readAsDataURL(file); });
$('#messages').addEventListener('click', e => { const promptButton = e.target.closest('[data-prompt]'); if (promptButton) { $('#promptInput').value = promptButton.dataset.prompt; $('#promptInput').focus(); return; } const fileButton = e.target.closest('[data-generated-file]'); if (fileButton) { const [messageIndex, fileIndex] = fileButton.dataset.generatedFile.split(':').map(Number); downloadGeneratedFile(messageIndex, fileIndex); return; } const zipButton = e.target.closest('[data-generated-zip]'); if (zipButton) { downloadGeneratedFile(Number(zipButton.dataset.generatedZip), 0, true); return; } handleMessageAction(e); });
$('#messages').addEventListener('scroll', () => { const quick = $('#scrollSettingsBtn'); if (quick) quick.hidden = $('#messages').scrollTop < 70; });
$('#scrollSettingsBtn').addEventListener('click', () => { openMenu(); const panel = $('#settingsPanel'); if (panel) { panel.hidden = false; syncSettingsPanel(); } });
$('#dismissNotice').addEventListener('click', () => $('#modeNotice').remove());
$('#clearBtn').addEventListener('click', () => { if (!state.messages.length || confirm(lang() === 'en' ? 'Clear current session?' : lang() === 'es' ? '¿Limpiar la sesión actual?' : 'Limpar a sessão atual?')) { state.messages = []; renderMessages(); } });
$('#exportBtn').addEventListener('click', () => { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), profile: state.profile, thinking: state.thinking, language: state.language, messages: state.messages }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `brown-ia-sessao-${Date.now()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); });
$('#settingsBtn').addEventListener('click', openMenu);
function appendMessageToChat(chatId, message) { if (state.chatId === chatId) { state.messages.push(message); return; } const chat = state.chats.find(entry => entry.id === chatId); if (chat) { chat.messages = normalizeMessages([...(chat.messages || []), message]); chat.updatedAt = Date.now(); } }
$('#composer').addEventListener('submit', async e => { e.preventDefault(); if (state.busy) return; const input = $('#promptInput'); await Promise.all([fileReady, providerReady]); const content = input.value.trim(); if (!content && !state.pendingFile) return; state.busy = true; state.lastRequestStatus = 'pending'; const requestId = ++state.requestSeq; const requestChatId = state.chatId; const started = performance.now(); const file = state.pendingFile; const messageText = content || `Leia e explique o arquivo anexado: ${file?.name || ''}`; if (Number.isInteger(state.editingIndex)) { state.messages = state.messages.slice(0, state.editingIndex); state.editingIndex = null; } appendMessageToChat(requestChatId, { role: 'user', content: messageText, attachmentName: file?.name || '', at: new Date().toISOString() }); input.value = ''; clearPendingFile(); renderMessages(); $('#statusText').textContent = state.connection === 'ready' ? 'GEMINI PROCESSING' : 'PROCESSING'; $('#latencyLabel').textContent = 'processando'; const sendButton = document.querySelector('.send-btn'); if (sendButton) sendButton.disabled = true; try { const answer = state.apiKey ? await geminiReply(messageText, file) : await new Promise(resolve => setTimeout(() => resolve(localReply(content)), 120)); if (requestId !== state.requestSeq) return; appendMessageToChat(requestChatId, { role: 'assistant', content: answer, at: new Date().toISOString() }); state.lastRequestStatus = 'success'; } catch (error) { if (requestId !== state.requestSeq) return; const quotaError = /429|quota|rate limit|resource exhausted|limit exceeded/i.test(error.message); if (quotaError) showQuotaFallback(error.message); setConnectionStatus('error', quotaError ? 'Provedor temporariamente indisponível' : 'Falha no arquivo ou no provedor'); state.lastRequestStatus = 'error'; appendMessageToChat(requestChatId, { role: 'assistant', content: `Não foi possível processar a solicitação: ${error.message}`, at: new Date().toISOString() }); } finally { if (requestId === state.requestSeq) { state.busy = false; if (sendButton) sendButton.disabled = false; if (state.connection === 'ready') $('#statusText').textContent = state.lastRequestStatus === 'error' ? 'GEMINI ERROR' : 'GEMINI READY'; else if (state.connection !== 'error') $('#statusText').textContent = 'LOCAL READY'; $('#latencyLabel').textContent = `${((performance.now() - started) / 1000).toFixed(1)}s`; if (state.chatId === requestChatId) renderMessages(); else persist(); } } });
$('#promptInput').addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); $('#composer').requestSubmit(); } });
setActive('.profile-btn','profile',state.profile); renderChatList(); renderProjects(); updateTags(); renderMessages();
