const STORAGE_KEY = 'brown-ia-session-v2';
const SETTINGS_KEY = 'brown-ia-settings-v1';
const KEY_STORAGE = 'brown-gemini-key-v1';
const FILE_DB = 'brown-ia-files-v1';
let fileReady;
const $ = (selector) => document.querySelector(selector);
const savedSettings = (() => { try { return JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}'); } catch { return {}; } })();
const state = { pendingFile: null, lastFile: null, textModel: null, profile: savedSettings.profile === 'GPT' ? 'BROWN' : (savedSettings.profile || 'BROWN'), thinking: savedSettings.thinking || 'MEDIO', language: savedSettings.language || 'pt-BR', messages: loadMessages(), apiKey: null, model: null };
const copy = {
  'pt-BR': { ready: 'Conversa pronta.', prompt: 'Faça uma pergunta, peça um plano ou descreva algo que a Brown deve criar.', greeting: 'Olá. Estou pronta para ajudar. Descreva o que você precisa fazer.', wellbeing: 'Tudo funcionando por aqui. Posso ajudar com conversa, código, pesquisa ou criação de arquivos.', demo: 'Entendi o pedido. Nesta primeira versão, estou no modo de demonstração local. O próximo conector permitirá gerar, validar e baixar arquivos reais com confirmação do resultado.', generic: p => `Recebi sua mensagem no perfil ${p}. O site está funcionando em modo local de demonstração; o próximo passo é conectar o provedor de IA com segurança.`, note: 'Brown responderá em português.', tag: 'PT-BR' },
  en: { ready: 'Conversation ready.', prompt: 'Ask a question, request a plan, or describe something Brown should create.', greeting: 'Hello. I am ready to help. Tell me what you need to do.', wellbeing: 'Everything is working. I can help with conversation, code, research, or file creation.', demo: 'I understood the request. This first version is running in local demo mode. The next connector will generate, validate, and download real files.', generic: p => `I received your message in the ${p} profile. The site is running in local demo mode; the next step is to connect the AI provider securely.`, note: 'Brown will respond in English.', tag: 'EN' },
  es: { ready: 'Conversación lista.', prompt: 'Haz una pregunta, pide un plan o describe algo que Brown deba crear.', greeting: 'Hola. Estoy lista para ayudar. Describe lo que necesitas hacer.', wellbeing: 'Todo funciona correctamente. Puedo ayudar con conversación, código, investigación o archivos.', demo: 'Entendí la solicitud. Esta primera versión funciona en modo de demostración local. El próximo conector generará y validará archivos reales.', generic: p => `Recibí tu mensaje en el perfil ${p}. El sitio funciona en modo local; el siguiente paso es conectar el proveedor de IA de forma segura.`, note: 'Brown responderá en español.', tag: 'ES' }
};
function lang() { return state.language === 'auto' ? 'pt-BR' : state.language; }
function t(key, ...args) { const value = copy[lang()][key]; return typeof value === 'function' ? value(...args) : value; }
function openFileDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(FILE_DB, 1); request.onupgradeneeded = () => request.result.createObjectStore('attachments'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function saveLastFile(file) { try { const db = await openFileDb(); db.transaction('attachments', 'readwrite').objectStore('attachments').put(file, 'last'); } catch {} }
async function loadLastFile() { try { const db = await openFileDb(); return await new Promise(resolve => { const request = db.transaction('attachments').objectStore('attachments').get('last'); request.onsuccess = () => resolve(request.result || null); request.onerror = () => resolve(null); }); } catch { return null; } }
fileReady = loadLastFile().then(file => { if (file) state.lastFile = file; });
function loadMessages() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); } catch { return []; } }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.messages.map(({ imageData, ...message }) => message))); localStorage.setItem(SETTINGS_KEY, JSON.stringify({ profile: state.profile, thinking: state.thinking, language: state.language })); $('#messageCount').textContent = state.messages.length; }
function formatContent(value) { const escaped = escapeText(value); return escaped.replace(/(https?:\/\/[^\s<]+)/g, '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>'); }
function escapeText(value) { return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function renderMessages() {
  const root = $('#messages');
  if (!state.messages.length) { root.innerHTML = `<div class="empty-state" id="emptyState"><div class="empty-glyph">BR</div><div class="empty-kicker">SYSTEM ONLINE · READY FOR INPUT</div><h2>${t('ready')}</h2><p>${t('prompt')}</p><div class="quick-prompts"><button data-prompt="Explique como você pode me ajudar.">Conhecer a Brown <span>↗</span></button><button data-prompt="Crie um plano profissional para meu projeto.">Criar um plano <span>↗</span></button><button data-prompt="Analise esta ideia e sugira melhorias.">Analisar uma ideia <span>↗</span></button></div></div>`; persist(); return; }
  root.innerHTML = state.messages.map(m => `<article class="message ${m.role}"><div class="avatar">${m.role === 'user' ? 'OP' : 'BR'}</div><div class="message-body"><div class="message-label">${m.role === 'user' ? 'OPERADOR' : 'BROWN'}</div><div class="message-content">${formatContent(m.content)}${m.role === 'assistant' ? `<a class=\"download-response\" href=\"data:text/markdown;charset=utf-8,${encodeURIComponent(m.content)}\" download=\"brown-resposta.md\">Baixar resposta .md</a>` : ''}${m.attachmentName ? `<div class=\"attachment-chip\">📎 ${escapeText(m.attachmentName)}</div>` : ''}</div></div></article>`).join(''); root.scrollTop = root.scrollHeight; persist();
}
function localReply(input) { const text = input.toLowerCase().trim(); if (/^(oi|olá|ola|hello|hi|hola|e aí|e ai|bom dia|boa tarde|boa noite)[!. ]*$/.test(text)) return t('greeting'); if (/^(tudo bem|how are you|todo bien)/.test(text)) return t('wellbeing'); if (text.includes('gemini')) return lang() === 'en' ? 'The Gemini connector is not active yet. The interface is ready for a secure backend without exposing the key in the browser.' : lang() === 'es' ? 'El conector Gemini aún no está activo. La interfaz está preparada para un backend seguro sin exponer la clave.' : 'O conector Gemini ainda não está ativo nesta versão. A interface está preparada para receber um backend seguro sem expor a chave no navegador.'; if (text.includes('arquivo') || text.includes('html') || text.includes('código') || text.includes('codigo') || text.includes('file') || text.includes('code')) return t('demo'); return t('generic', state.profile); }
function fetchWithTimeout(url, options = {}, ms = 30000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), ms); return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timer)).catch(error => { if (error.name === 'AbortError') throw new Error('A Gemini demorou mais de 30 segundos para responder.'); throw new Error('Não foi possível alcançar a Gemini. Verifique sua conexão e as permissões da chave.'); }); }
async function validateGeminiKey(key) { const response = await fetchWithTimeout(`https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(key)}`, {}, 10000); let payload = {}; try { payload = await response.json(); } catch {} if (!response.ok) { const message = payload?.error?.message || `HTTP ${response.status}`; throw new Error(message.replace(/AIza\S+/g, '[chave omitida]')); } const models = (payload.models || []).filter(model => (model.supportedGenerationMethods || []).includes('generateContent')); const names = models.map(model => String(model.name || '').replace(/^models\//, '')); const preferred = ['gemini-3.5-flash-lite','gemini-2.0-flash-lite','gemini-3.8-flash-lite','gemini-3.8-flash','gemini-3.5-flash','gemini-2.5-flash','gemini-2.0-flash','gemini-1.5-flash']; const selected = preferred.find(name => names.includes(name)) || names.find(name => /flash.*lite/i.test(name)) || names.find(name => /flash/i.test(name)); if (!selected) throw new Error('A chave é válida, mas nenhum modelo Flash compatível foi encontrado.'); return { selected }; }
async function geminiReply(input, file = null) { const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${state.model}:generateContent?key=${encodeURIComponent(state.apiKey)}`; const history = state.messages.slice(-12).map(m => ({ role: m.role === 'assistant' ? 'model' : 'user', parts: [{ text: m.content.slice(0, 6000) }] })); if (file && history.length) { history[history.length - 1].parts[0].text += `\n\n[Arquivo anexado: ${file.name} | MIME: ${file.mimeType}]`; if (/^(text\/|application\/(pdf|json|xml)|text\/csv)/i.test(file.mimeType)) history[history.length - 1].parts.push({ inlineData: { mimeType: file.mimeType, data: file.base64 } }); } const codeTask = /(c[oó]digo|programa|script|html|css|javascript|python|bash|terminal|fun[cç][aã]o|bug|erro|arquivo|documento)/i.test(input); const researchTask = /(pesquise|pesquisa|compare|fontes|referências|hist[oó]ria|dados|atual|link)/i.test(input); const fileTask = Boolean(file); const thinkingGuide = { LEVE: 'Resolva rapidamente. Faça uma verificação curta e entregue a resposta direta, sem sacrificar o dado essencial.', MEDIO: 'Analise o pedido em etapas internas, confira a lógica principal e entregue uma resposta equilibrada.', ALTO: 'Faça uma análise cuidadosa, considere casos-limite, valide a solução e explique as decisões importantes.', EXTREMO: 'Faça uma revisão rigorosa de requisitos, consistência, exceções e completude antes de responder; entregue a solução integral.' }[state.thinking] || 'Analise e responda com equilíbrio.'; const links = input.match(/https?:\/\/[^\s)]+/gi) || []; const system = `Você é Brown, uma assistente profissional, versátil e prática. Perfil: ${state.profile}. Nível de raciocínio: ${state.thinking}. ${thinkingGuide} Idioma obrigatório: ${lang()}. Tarefa de código/documento: ${codeTask ? 'sim' : 'não'}. Tarefa de pesquisa: ${researchTask ? 'sim' : 'não'}. Arquivo anexado: ${fileTask ? `${file.name} (${file.mimeType})` : 'não'}.

Responda ao pedido real, sem saudações automáticas, persona teatral, status inventado ou explicações sobre ser uma IA. Não diga que é incapaz de fazer algo apenas por ser uma assistente de texto. Para pedidos benignos, tente resolver diretamente. Não use recusas genéricas: explique somente uma limitação concreta quando ela realmente existir. Não invente fatos, resultados de ferramentas, acesso a links ou alterações que não foram executadas.

Para código e arquivos: entregue conteúdo completo, funcional e autocontido quando solicitado; não corte no meio, não substitua partes por TODO, não omita arquivos necessários e preserve o formato. Quando houver um arquivo anexado, trate-o como fonte e, se pedirem alteração, devolva a versão completa revisada com nome/extensão sugeridos. Quando o conteúdo for grande, organize em partes numeradas completas e avise exatamente onde cada parte começa/termina.

Para pesquisa: diferencie fatos, inferências e incertezas. Para links, use somente o conteúdo fornecido ou acessível pela ferramenta; nunca finja ter aberto a página. Use Markdown apenas quando melhorar a leitura. Não revele raciocínio interno passo a passo; forneça conclusões, verificações e justificativas úteis. Só recuse pedidos que envolvam dano grave, crime ou abuso perigoso; para pedidos permitidos, seja útil e objetiva. Links detectados: ${links.join(', ') || 'nenhum'}.`; const outputLimit = codeTask ? (state.thinking === 'LEVE' ? 2048 : state.thinking === 'MEDIO' ? 4096 : state.thinking === 'ALTO' ? 8192 : 8192) : (state.thinking === 'LEVE' ? 768 : state.thinking === 'MEDIO' ? 1536 : state.thinking === 'ALTO' ? 3072 : 4096); const response = await fetchWithTimeout(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents: history, generationConfig: { temperature: state.thinking === 'LEVE' ? 0.7 : state.thinking === 'MEDIO' ? 0.55 : state.thinking === 'ALTO' ? 0.45 : 0.35, maxOutputTokens: outputLimit } }) }, 20000); let payload = {}; try { payload = await response.json(); } catch {} if (!response.ok) { const message = payload?.error?.message || `HTTP ${response.status}`; throw new Error(message.replace(/AIza\S+/g, '[chave omitida]')); } const text = payload?.candidates?.[0]?.content?.parts?.map(part => part.text || '').join('').trim(); if (!text) throw new Error('A Gemini não retornou texto.'); return text; }
function setConnectionStatus(status, message) { const card = document.querySelector('.model-card'); const led = $('#modelLed'); const label = $('#modelStatus'); card.classList.remove('connected','error'); if (status === 'connected') { card.classList.add('connected'); led.style.background = ''; label.textContent = message || 'Chave ativa nesta aba'; $('#modeTitle').textContent = 'Gemini conectado nesta aba'; $('#modeDescription').textContent = 'As mensagens serão enviadas ao modelo selecionado. A chave fica nesta aba e, se marcado, neste navegador.'; $('#statusText').textContent = 'GEMINI READY'; } else if (status === 'error') { card.classList.add('error'); label.textContent = message || 'Falha na conexão'; $('#statusText').textContent = 'GEMINI ERROR'; } else { label.textContent = 'Conexão segura pendente'; $('#statusText').textContent = 'LOCAL READY'; } }
function updateTags() { $('#channelTitle').textContent = state.profile === 'BROWN' ? 'Brown' : state.profile; $('#profileTag').textContent = state.profile; $('#thinkingTag').textContent = state.thinking === 'MEDIO' ? 'MÉDIO' : state.thinking; $('#thinkingButtonLabel').textContent = state.thinking === 'MEDIO' ? 'MÉDIO' : state.thinking; $('#languageTag').textContent = copy[lang()].tag; $('#languageNote').textContent = t('note'); $('#languageSelect').value = state.language; }
function setActive(selector, attr, value) { document.querySelectorAll(selector).forEach(el => el.classList.toggle('active', el.dataset[attr] === value)); }
$('#profileList').addEventListener('click', e => { const btn = e.target.closest('[data-profile]'); if (!btn) return; state.profile = btn.dataset.profile; setActive('.profile-btn','profile',state.profile); updateTags(); persist(); });
$('#thinkingButton').addEventListener('click', () => { const menu = $('#thinkingMenu'); const open = menu.hidden; menu.hidden = !open; $('#thinkingButton').setAttribute('aria-expanded', String(open)); });
$('#thinkingMenu').addEventListener('click', e => { const btn = e.target.closest('[data-thinking]'); if (!btn) return; state.thinking = btn.dataset.thinking; updateTags(); persist(); $('#thinkingMenu').hidden = true; $('#thinkingButton').setAttribute('aria-expanded', 'false'); });
document.addEventListener('click', e => { if (!e.target.closest('.reasoning-picker')) { $('#thinkingMenu').hidden = true; $('#thinkingButton').setAttribute('aria-expanded', 'false'); } });
$('#languageSelect').addEventListener('change', e => { state.language = e.target.value; updateTags(); renderMessages(); });
async function connectGemini(value, silent = false) { const button = $('#connectBtn'); if (!value) { state.apiKey = null; state.model = null; state.textModel = null;  if (!silent) setConnectionStatus('idle'); return; } if (!silent) { button.disabled = true; button.textContent = 'TESTANDO'; } try { const models = await validateGeminiKey(value); state.model = models.selected; state.textModel = models.selected; state.apiKey = value; if ($('#saveKeyInput').checked) localStorage.setItem(KEY_STORAGE, value); else localStorage.removeItem(KEY_STORAGE); $('#apiKeyInput').value = ''; setConnectionStatus('connected', `Ativa · ${state.model}`); } catch (error) { state.apiKey = null; state.model = null; state.textModel = null;  if (!silent) setConnectionStatus('error', error.message); } finally { if (!silent) { button.disabled = false; button.textContent = 'CONECTAR'; } } }
$('#connectBtn').addEventListener('click', () => connectGemini($('#apiKeyInput').value.trim()));
$('#saveKeyInput').addEventListener('change', e => { if (!e.target.checked) localStorage.removeItem(KEY_STORAGE); else if (state.apiKey) localStorage.setItem(KEY_STORAGE, state.apiKey); });
const storedKey = localStorage.getItem(KEY_STORAGE); if (storedKey) { $('#saveKeyInput').checked = true; connectGemini(storedKey, true); }


function clearPendingFile() { state.pendingFile = null; state.model = state.textModel || state.model; $('#fileInput').value = ''; $('#attachmentPreview').hidden = true; $('#attachmentPreview').innerHTML = ''; }
function showPendingFile(file) { $('#attachmentPreview').hidden = false; $('#attachmentPreview').innerHTML = `<span class="file-glyph">DOC</span><span>${escapeText(file.name)} · ${escapeText(file.mimeType || 'arquivo')}</span><button type="button" id="removeFile" aria-label="Remover anexo">×</button>`; $('#removeFile').addEventListener('click', clearPendingFile); }
$('#fileButton').addEventListener('click', () => $('#fileInput').click());
$('#fileInput').addEventListener('change', e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 20 * 1024 * 1024) { alert('O arquivo deve ter no máximo 20 MB.'); e.target.value = ''; return; } const reader = new FileReader(); reader.onload = () => { const dataUrl = String(reader.result); state.pendingFile = { name: file.name, mimeType: file.type || 'application/octet-stream', dataUrl, base64: dataUrl.split(',')[1] || '', size: file.size }; state.lastFile = state.pendingFile; saveLastFile(state.pendingFile); showPendingFile(state.pendingFile); }; reader.readAsDataURL(file); });
$('#messages').addEventListener('click', e => { const button = e.target.closest('[data-prompt]'); if (!button) return; $('#promptInput').value = button.dataset.prompt; $('#promptInput').focus(); });
$('#dismissNotice').addEventListener('click', () => $('#modeNotice').remove());
$('#clearBtn').addEventListener('click', () => { if (!state.messages.length || confirm(lang() === 'en' ? 'Clear current session?' : lang() === 'es' ? '¿Limpiar la sesión actual?' : 'Limpar a sessão atual?')) { state.messages = []; renderMessages(); } });
$('#exportBtn').addEventListener('click', () => { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), profile: state.profile, thinking: state.thinking, language: state.language, messages: state.messages }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `brown-ia-sessao-${Date.now()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); });
$('#settingsBtn').addEventListener('click', () => alert(lang() === 'en' ? 'Advanced settings will be added with the secure provider.' : lang() === 'es' ? 'La configuración avanzada llegará con el proveedor seguro.' : 'Configurações avançadas serão adicionadas quando o backend seguro estiver conectado.'));
$('#composer').addEventListener('submit', async e => { e.preventDefault(); const input = $('#promptInput'); await fileReady; const content = input.value.trim(); if (!content && !state.pendingFile && !state.lastFile) return; const started = performance.now(); const file = state.pendingFile || state.lastFile; if (state.pendingFile) { state.lastFile = state.pendingFile; saveLastFile(state.lastFile); } const messageText = content || `Leia e explique o arquivo anexado: ${file?.name || ''}`; state.messages.push({ role: 'user', content: messageText, attachmentName: file?.name || '', at: new Date().toISOString() }); input.value = ''; clearPendingFile(); renderMessages(); $('#statusText').textContent = state.apiKey ? 'GEMINI PROCESSING' : 'PROCESSING'; $('#latencyLabel').textContent = 'processando'; try { const answer = state.apiKey ? await geminiReply(messageText, file) : await new Promise(resolve => setTimeout(() => resolve(localReply(content)), 120)); state.messages.push({ role: 'assistant', content: answer, at: new Date().toISOString() }); } catch (error) { setConnectionStatus('error', 'Falha no arquivo ou na chave'); state.messages.push({ role: 'assistant', content: `Não foi possível processar o anexo: ${error.message}`, at: new Date().toISOString() }); } renderMessages(); const ms = ((performance.now() - started) / 1000).toFixed(1); $('#statusText').textContent = state.apiKey ? 'GEMINI READY' : 'LOCAL READY'; $('#latencyLabel').textContent = `${ms}s · ${state.apiKey ? 'Gemini' : 'modo local'}`; });
$('#promptInput').addEventListener('keydown', e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); $('#composer').requestSubmit(); } });
setActive('.profile-btn','profile',state.profile); updateTags(); renderMessages();
